-- migrate:up

-- Generic, provider-agnostic app installations: the multi-tenant record of "Lobu
-- App <X> is installed into external tenant <Y>". This replaces the bespoke
-- per-provider install tables (e.g. slack_installations) with one model that
-- covers GitHub Apps (installation_id), Slack OAuth v2 (team_id), and Jira/
-- Atlassian Connect (cloudId) under a single routing + ownership contract.
--
-- WHY a dedicated table (not agent_connections): an installation is an org/tenant
-- INSTALLATION resource, not an agent's connection. One installed tenant routes
-- to MANY agents via channel bindings, so it has no single owning agent;
-- modeling it as an agent_connections row would force a synthetic placeholder
-- agent and couple the tenant lifecycle to a deletable agent.
--
-- Credentials live in auth_profiles (token / app-secret refs) — never plaintext
-- here. `auth_profile_id` is the credential backing; `metadata` carries
-- provider-specific tenant data (team_name, account login, site url, etc.).
--
-- Routing: the shared webhook endpoint (e.g. /github/events, /slack/events)
-- carries no org context. It resolves the install by the provider tenant tuple
-- (provider, provider_instance, provider_app_id, external_tenant_id) alone, then
-- fans out to the org's agents. The route index below serves that lookup.
--
-- Ownership (reject/transfer): exactly ONE active install may own a given
-- external tenant tuple at a time. A re-install from the same org updates in
-- place; an install from a DIFFERENT org TRANSFERS ownership (the prior active
-- row is demoted, the new one activated) so routing stays unambiguous. The
-- partial unique index `app_installations_active_tenant` enforces the invariant
-- in Postgres — it is the source of truth, so concurrent callers across replicas
-- converge to a single active owner without any in-memory coordination.
CREATE TABLE IF NOT EXISTS public.app_installations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,   -- bigint-id convention (auth_profiles / agent_grants)
    organization_id text NOT NULL,
    provider text NOT NULL,                       -- 'github' | 'slack' | 'jira'
    provider_instance text NOT NULL DEFAULT 'cloud', -- 'cloud' | GHES host | atlassian site class
    provider_app_id text NOT NULL,                -- which Lobu App
    external_tenant_id text NOT NULL,             -- installation_id / team_id / cloudId
    auth_profile_id bigint,                       -- credential backing (token / app-secret refs)
    status text NOT NULL,                         -- active | suspended | revoked | error | pending
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT app_installations_pkey PRIMARY KEY (id),
    CONSTRAINT app_installations_status_check
        CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text, 'revoked'::text, 'error'::text, 'pending'::text]))),
    CONSTRAINT app_installations_org_fkey
        FOREIGN KEY (organization_id) REFERENCES public.organization(id) ON DELETE CASCADE,
    CONSTRAINT app_installations_auth_profile_fkey
        FOREIGN KEY (auth_profile_id) REFERENCES public.auth_profiles(id)
);

-- migrate:down

-- squawk-ignore ban-drop-table
DROP TABLE IF EXISTS public.app_installations;
