-- migrate:up

-- Org-owned inference provider credentials with per-modality custom upstreams.
--
-- Each row is one named provider credential for an org (slug-referenced by agents).
-- `capabilities` jsonb carries per-modality config { "<modality>": { base_url?, model?,
-- models_endpoint? } } where modality ∈ text|image|stt|tts|embedding. An absent
-- modality block ⇒ fall back to today's static/hardcoded behavior for that modality (so existing
-- orgs are byte-identical at cutover); a present block with a non-null base_url ⇒ that modality's
-- calls use the org credential ONLY (the URL invariant — never per-user, never process.env).
--
-- The DDL CHECKs are the UNCONDITIONAL security floor under the app-layer validator: any write path
-- (backfill, repair job, a raw jsonb_set) hits them. All CHECKs verified on PostgreSQL 18.1 (the
-- product's embedded major).

CREATE TABLE IF NOT EXISTS public.inference_providers (
    -- BY DEFAULT is LOAD-BEARING: api_key_ref embeds <id>, minted via the identity sequence before a
    -- single atomic INSERT with an explicit id. GENERATED ALWAYS would forbid the explicit id.
    id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     text        NOT NULL,
    slug                text        NOT NULL,            -- agent-referenced, immutable, lowercase-kebab
    kind                text        NOT NULL,            -- provider TYPE (openai/groq/gemini/…); NOT sdkCompat
    display_name        text,
    api_key_ref         text        NOT NULL,            -- "secret://<org>/<slug>-<id>" — row-unique, immutable
    -- Per-modality config. Shape: { "<modality>": { base_url?, model?, models_endpoint? } }
    --   modality ∈ text|image|stt|tts|embedding
    -- ONE credential per row (no per-modality key): a row with any custom upstream is org-key-only
    -- across every modality it serves. An org wanting a static-modality + custom-modality split with
    -- different keys makes TWO provider rows (two slugs) — this keeps the credential atomic to the row
    -- and removes the "secret embedded in tenant-writable jsonb" class entirely.
    capabilities        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    -- Coarse "does ANY modality have a custom upstream" flag — a list/index aid ONLY. The per-call gate
    -- is the INVOKED modality's base_url, not this column. GENERATED so it can't drift. `@?` is IMMUTABLE.
    has_custom_upstream boolean     GENERATED ALWAYS AS (
        capabilities @? '$.* ? (@.base_url != null)'
    ) STORED,
    status              text        NOT NULL DEFAULT 'active',
    error_message       text,
    created_by          text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz,

    CONSTRAINT inference_providers_status_check
        CHECK (status = ANY (ARRAY['active', 'disabled', 'error'])),

    -- No kind CHECK: kind = provider type; sdkCompat lives in providers.json and is enforced
    -- server-side on base_url writes. A DB enum would abort the backfill and drift on every provider add.
    -- Slug shape MUST match the CLI (map-config ORG_PROVIDER_SLUG_PATTERN) + backfill
    -- exactly: lowercase alphanumeric + hyphen, 1-63 chars, no leading/trailing hyphen.
    -- The optional group makes a single-char slug legal while still rejecting a
    -- trailing hyphen — the old `[a-z0-9-]{0,62}[a-z0-9]` required >=2 chars.
    CONSTRAINT inference_providers_slug_format
        CHECK (slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'),

    -- capabilities keys must be known modalities. Subquery-free (a subquery is rejected in a CHECK).
    -- The jsonb_typeof guard is load-bearing: without it, `-` (jsonb minus text[]) on an ARRAY value
    -- deletes elements instead of erroring, letting ["text"] slip through. `caps - ARRAY[...] = '{}'`
    -- means no key remains after removing the known modalities ⇒ every key is known.
    CONSTRAINT inference_providers_capabilities_keys
        CHECK (jsonb_typeof(capabilities) = 'object'
               AND capabilities - ARRAY['text', 'image', 'stt', 'tts', 'embedding'] = '{}'::jsonb),

    -- Every modality BODY must be an object: closes the raw-write gap where {"text": 5} or
    -- {"text":"https://evil"} passed every other CHECK (a scalar body no jsonpath inspected for base_url).
    CONSTRAINT inference_providers_capabilities_bodies
        CHECK (NOT (capabilities @? '$.* ? (@.type() != "object")')),

    -- DB backstop: ban user:pass@ userinfo in any base_url (audit-plaintext credential leak).
    CONSTRAINT inference_providers_no_userinfo
        CHECK (NOT (capabilities @? '$.* ? (@.base_url like_regex "^[^/]*//[^/@]*@")')),

    -- DB backstop: models_endpoint must be a relative path, never a URL. POSITIVE WHITELIST so the DB
    -- floor equals the app-layer charset rule exactly and no out-of-set byte can bypass it — including
    -- tab/LF/CR, which WHATWG new URL() strips before parsing (so "/<TAB>//evil" would resolve off-host).
    -- The explicit `not starts with "//"` is required because "//" is charset-legal but protocol-relative.
    CONSTRAINT inference_providers_me_path_only
        CHECK (NOT (capabilities @? '$.* ? (@.models_endpoint != null && (@.models_endpoint.type() != "string" || !(@.models_endpoint like_regex "^/[A-Za-z0-9/_.-]*$") || @.models_endpoint starts with "//"))'))
);

-- api_key_ref is a row-unique name (<slug>-<id>) so a soft-delete→recreate never collides and a new
-- row can't inherit a deleted row's ciphertext. TOTAL index (no deleted_at filter) so a soft-deleted
-- row still reserves its ref.
-- squawk-ignore require-concurrent-index-creation -- brand-new empty table; nothing to lock, and dbmate wraps in a transaction
CREATE UNIQUE INDEX IF NOT EXISTS inference_providers_keyref_unique
    ON public.inference_providers (api_key_ref);

-- One live slug per org (soft-delete aware — mirrors connections_org_slug_unique).
-- squawk-ignore require-concurrent-index-creation -- brand-new empty table; nothing to lock, and dbmate wraps in a transaction
CREATE UNIQUE INDEX IF NOT EXISTS inference_providers_org_slug_live
    ON public.inference_providers (organization_id, slug) WHERE (deleted_at IS NULL);

-- squawk-ignore require-concurrent-index-creation -- brand-new empty table; nothing to lock, and dbmate wraps in a transaction
CREATE INDEX IF NOT EXISTS inference_providers_org_live
    ON public.inference_providers (organization_id) WHERE (deleted_at IS NULL);

-- squawk-ignore require-concurrent-index-creation -- brand-new empty table; nothing to lock, and dbmate wraps in a transaction
CREATE INDEX IF NOT EXISTS inference_providers_capabilities_gin
    ON public.inference_providers USING gin (capabilities);

-- migrate:down

-- squawk-ignore ban-drop-table -- rollback of a same-PR new table; no external clients depend on it yet
DROP TABLE IF EXISTS public.inference_providers;
