/**
 * Embedding Utilities
 *
 * Helper functions for working with semantic embeddings.
 *
 * IMPORTANT: Embeddings are generated by a dedicated embeddings service or external workers.
 * This module provides utilities for manipulating embeddings, plus a client to request
 * embeddings from the service when needed (e.g., classifier values).
 */

import type { Env } from '../index';
import logger from '../utils/logger';

const EMBEDDING_DIMENSIONS = 768;
// Must match @lobu/embeddings DEFAULT_MODEL_NAME (the local pipeline + service
// fall back to this when EMBEDDINGS_MODEL is unset).
export const DEFAULT_EMBEDDING_MODEL = 'Xenova/bge-base-en-v1.5';
// Allowlist mirroring the embeddings service's MODEL_NAME_PATTERN. Used to
// reject anything unsafe before inlining the configured model into SQL.
const MODEL_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/:-]{0,127}$/;

/**
 * The embedding model this deployment is configured to produce/consume. Every
 * freshly-written event_embeddings row is stamped with this, and similarity
 * queries scope to it so a same-dimension model swap can't compare vectors
 * across incompatible spaces. Reads the same env var (with the same default)
 * as the worker and the embeddings service.
 */
export function getConfiguredEmbeddingModel(): string {
  return process.env.EMBEDDINGS_MODEL || DEFAULT_EMBEDDING_MODEL;
}

/**
 * SQL-safe string literal for the configured model, for inlining into a query
 * builder where threading another bound parameter would be error-prone. The
 * value is server config (not user input); we still validate it against the
 * service's model-name allowlist and reject otherwise — fail closed rather than
 * risk injection.
 */
export function configuredEmbeddingModelSqlLiteral(): string {
  const model = getConfiguredEmbeddingModel();
  if (!MODEL_NAME_PATTERN.test(model)) {
    throw new Error(
      `EMBEDDINGS_MODEL '${model}' is not a valid model identifier (allowed: ${MODEL_NAME_PATTERN}).`
    );
  }
  return `'${model}'`;
}
const DEFAULT_TIMEOUT_MS = 30000;

function resolveEmbeddingServiceUrl(env: Env): string {
  const url = env.EMBEDDINGS_SERVICE_URL?.trim();
  if (!url) {
    throw new Error(
      'EMBEDDINGS_SERVICE_URL is required to generate embeddings. ' +
        'Configure the embeddings service or provide embeddings directly.'
    );
  }
  return url.replace(/\/+$/, '');
}

/**
 * Validate that the embeddings service is reachable and healthy.
 * Call this before attempting to generate embeddings to fail fast with a clear error.
 *
 * @throws Error if service is unavailable or unhealthy
 */
export async function validateEmbeddingsService(env: Env): Promise<void> {
  const url = resolveEmbeddingServiceUrl(env);

  try {
    const response = await fetch(`${url}/health`, {
      method: 'GET',
      signal: AbortSignal.timeout(5000),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => '');
      throw new Error(
        `Embeddings service unhealthy (${response.status}): ${errorText.slice(0, 200)}`
      );
    }

    const health = (await response.json()) as { ok?: boolean };
    if (!health.ok) {
      throw new Error('Embeddings service returned unhealthy status');
    }

    logger.debug({ url }, '[Embeddings] Service health check passed');
  } catch (error) {
    if (error instanceof Error && error.message.includes('unhealthy')) {
      throw error;
    }
    throw new Error(
      `Embeddings service unavailable at ${url}. ` +
        'Cannot save watcher window without generating embeddings. ' +
        'Start the embeddings service or provide embeddings in extracted_data. ' +
        `Original error: ${error instanceof Error ? error.message : 'Unknown'}`
    );
  }
}

/**
 * Generate embeddings for multiple texts via the embeddings service.
 *
 * @param texts - Array of texts to embed
 * @param env - Environment with embeddings service configuration
 * @returns Array of 768-dimensional embedding vectors
 */
export async function generateEmbeddings(texts: string[], env: Env, signal?: AbortSignal): Promise<number[][]> {
  if (texts.length === 0) {
    return [];
  }

  const url = resolveEmbeddingServiceUrl(env);
  const parsedTimeout = Number.parseInt(env.EMBEDDINGS_TIMEOUT_MS || '', 10);
  const timeoutMs = Number.isFinite(parsedTimeout) ? parsedTimeout : DEFAULT_TIMEOUT_MS;
  const controller = new AbortController();
  const abortFromCaller = () => controller.abort(signal?.reason);
  if (signal?.aborted) abortFromCaller(); else signal?.addEventListener('abort', abortFromCaller, { once: true });
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    if (env.EMBEDDINGS_SERVICE_TOKEN) {
      headers.Authorization = `Bearer ${env.EMBEDDINGS_SERVICE_TOKEN}`;
    }

    const response = await fetch(`${url}/api/embeddings`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ texts }),
      signal: controller.signal,
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Embeddings service error (${response.status}): ${errorText.slice(0, 300)}`);
    }

    const payload = (await response.json()) as {
      embeddings?: number[][];
      dimensions?: number;
      model?: string;
    };

    if (!Array.isArray(payload.embeddings)) {
      throw new Error('Embeddings service response missing embeddings array');
    }

    if (payload.embeddings.length !== texts.length) {
      throw new Error(
        `Embeddings service returned ${payload.embeddings.length} embeddings for ${texts.length} texts`
      );
    }

    if (payload.dimensions && payload.dimensions !== EMBEDDING_DIMENSIONS) {
      throw new Error(
        `Embeddings service returned ${payload.dimensions} dimensions (expected ${EMBEDDING_DIMENSIONS})`
      );
    }

    const invalidIndex = payload.embeddings.findIndex((embedding) => !isValidEmbedding(embedding));
    if (invalidIndex !== -1) {
      throw new Error(`Embeddings service returned invalid embedding at index ${invalidIndex}`);
    }

    // Version-stamp guard: the query vector we are about to compare against
    // stored rows MUST come from the same model those rows are scoped to. If the
    // service reports a different model, fail loud rather than silently
    // comparing across incompatible vector spaces.
    if (payload.model) {
      const configuredModel = getConfiguredEmbeddingModel();
      if (payload.model !== configuredModel) {
        throw new Error(
          `Embeddings service returned model '${payload.model}' but this deployment is ` +
            `configured for '${configuredModel}'. Refusing to compare across incompatible ` +
            `vector spaces — align EMBEDDINGS_MODEL on the server and the embeddings service.`
        );
      }
      logger.debug({ model: payload.model }, '[Embeddings] Service model');
    }

    return payload.embeddings;
  } finally {
    clearTimeout(timeout);
    signal?.removeEventListener('abort', abortFromCaller);
  }
}

/**
 * Validate embedding dimensions
 *
 * @param embedding - Embedding to validate
 * @param expectedDimensions - Expected dimensions (default: 768)
 * @returns true if valid, false otherwise
 */
export function isValidEmbedding(
  embedding: number[] | null | undefined,
  expectedDimensions: number = EMBEDDING_DIMENSIONS
): embedding is number[] {
  return (
    Array.isArray(embedding) &&
    embedding.length === expectedDimensions &&
    embedding.every((n) => typeof n === 'number' && !Number.isNaN(n))
  );
}
