/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as OwnerIndexRouteImport } from './app/$owner/index'
import { Route as OauthDeviceRouteImport } from './app/oauth/device'
import { Route as OauthConsentRouteImport } from './app/oauth/consent'
import { Route as AuthResetPasswordRouteImport } from './app/auth/reset-password'
import { Route as AuthLogoutRouteImport } from './app/auth/logout'
import { Route as AuthLoginRouteImport } from './app/auth/login'
import { Route as AuthCallbackRouteImport } from './app/auth/callback'
import { Route as AuthAcceptInvitationRouteImport } from './app/auth/accept-invitation'
import { Route as AuthPathnameRouteImport } from './app/auth/$pathname'
import { Route as AccountSettingsRouteImport } from './app/account/settings'
import { Route as OwnerAgentsRouteImport } from './app/$owner/agents'
import { Route as OwnerSplatRouteImport } from './app/$owner/$'
import { Route as OwnerWatchersIndexRouteImport } from './app/$owner/watchers/index'
import { Route as OwnerMembersIndexRouteImport } from './app/$owner/members/index'
import { Route as OwnerEventsIndexRouteImport } from './app/$owner/events/index'
import { Route as OwnerConnectorsIndexRouteImport } from './app/$owner/connectors/index'
import { Route as OwnerAgentsIndexRouteImport } from './app/$owner/agents/index'
import { Route as OwnerEntityTypeIndexRouteImport } from './app/$owner/$entityType/index'
import { Route as OwnerWatchersWatcherIdRouteImport } from './app/$owner/watchers/$watcherId'
import { Route as OwnerMembersUserIdRouteImport } from './app/$owner/members/$userId'
import { Route as OwnerEventsEventIdRouteImport } from './app/$owner/events/$eventId'
import { Route as OwnerConnectorsConnectorKeyRouteImport } from './app/$owner/connectors/$connectorKey'
import { Route as OwnerAgentsAgentIdRouteImport } from './app/$owner/agents/$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthDeviceRoute = OauthDeviceRouteImport.update({
  id: '/oauth/device',
  path: '/oauth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInvitationRoute = AuthAcceptInvitationRouteImport.update({
  id: '/auth/accept-invitation',
  path: '/auth/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAgentsRoute = OwnerAgentsRouteImport.update({
  id: '/$owner/agents',
  path: '/$owner/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSplatRoute = OwnerSplatRouteImport.update({
  id: '/$owner/$',
  path: '/$owner/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerWatchersIndexRoute = OwnerWatchersIndexRouteImport.update({
  id: '/$owner/watchers/',
  path: '/$owner/watchers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMembersIndexRoute = OwnerMembersIndexRouteImport.update({
  id: '/$owner/members/',
  path: '/$owner/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEventsIndexRoute = OwnerEventsIndexRouteImport.update({
  id: '/$owner/events/',
  path: '/$owner/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerConnectorsIndexRoute = OwnerConnectorsIndexRouteImport.update({
  id: '/$owner/connectors/',
  path: '/$owner/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAgentsIndexRoute = OwnerAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerAgentsRoute,
} as any)
const OwnerEntityTypeIndexRoute = OwnerEntityTypeIndexRouteImport.update({
  id: '/$owner/$entityType/',
  path: '/$owner/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerWatchersWatcherIdRoute = OwnerWatchersWatcherIdRouteImport.update({
  id: '/$owner/watchers/$watcherId',
  path: '/$owner/watchers/$watcherId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMembersUserIdRoute = OwnerMembersUserIdRouteImport.update({
  id: '/$owner/members/$userId',
  path: '/$owner/members/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEventsEventIdRoute = OwnerEventsEventIdRouteImport.update({
  id: '/$owner/events/$eventId',
  path: '/$owner/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerConnectorsConnectorKeyRoute =
  OwnerConnectorsConnectorKeyRouteImport.update({
    id: '/$owner/connectors/$connectorKey',
    path: '/$owner/connectors/$connectorKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerAgentsAgentIdRoute = OwnerAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => OwnerAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner/$': typeof OwnerSplatRoute
  '/$owner/agents': typeof OwnerAgentsRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/device': typeof OauthDeviceRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/agents/$agentId': typeof OwnerAgentsAgentIdRoute
  '/$owner/connectors/$connectorKey': typeof OwnerConnectorsConnectorKeyRoute
  '/$owner/events/$eventId': typeof OwnerEventsEventIdRoute
  '/$owner/members/$userId': typeof OwnerMembersUserIdRoute
  '/$owner/watchers/$watcherId': typeof OwnerWatchersWatcherIdRoute
  '/$owner/$entityType/': typeof OwnerEntityTypeIndexRoute
  '/$owner/agents/': typeof OwnerAgentsIndexRoute
  '/$owner/connectors/': typeof OwnerConnectorsIndexRoute
  '/$owner/events/': typeof OwnerEventsIndexRoute
  '/$owner/members/': typeof OwnerMembersIndexRoute
  '/$owner/watchers/': typeof OwnerWatchersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$owner/$': typeof OwnerSplatRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/device': typeof OauthDeviceRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/agents/$agentId': typeof OwnerAgentsAgentIdRoute
  '/$owner/connectors/$connectorKey': typeof OwnerConnectorsConnectorKeyRoute
  '/$owner/events/$eventId': typeof OwnerEventsEventIdRoute
  '/$owner/members/$userId': typeof OwnerMembersUserIdRoute
  '/$owner/watchers/$watcherId': typeof OwnerWatchersWatcherIdRoute
  '/$owner/$entityType': typeof OwnerEntityTypeIndexRoute
  '/$owner/agents': typeof OwnerAgentsIndexRoute
  '/$owner/connectors': typeof OwnerConnectorsIndexRoute
  '/$owner/events': typeof OwnerEventsIndexRoute
  '/$owner/members': typeof OwnerMembersIndexRoute
  '/$owner/watchers': typeof OwnerWatchersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner/$': typeof OwnerSplatRoute
  '/$owner/agents': typeof OwnerAgentsRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/device': typeof OauthDeviceRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/agents/$agentId': typeof OwnerAgentsAgentIdRoute
  '/$owner/connectors/$connectorKey': typeof OwnerConnectorsConnectorKeyRoute
  '/$owner/events/$eventId': typeof OwnerEventsEventIdRoute
  '/$owner/members/$userId': typeof OwnerMembersUserIdRoute
  '/$owner/watchers/$watcherId': typeof OwnerWatchersWatcherIdRoute
  '/$owner/$entityType/': typeof OwnerEntityTypeIndexRoute
  '/$owner/agents/': typeof OwnerAgentsIndexRoute
  '/$owner/connectors/': typeof OwnerConnectorsIndexRoute
  '/$owner/events/': typeof OwnerEventsIndexRoute
  '/$owner/members/': typeof OwnerMembersIndexRoute
  '/$owner/watchers/': typeof OwnerWatchersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner/$'
    | '/$owner/agents'
    | '/account/settings'
    | '/auth/$pathname'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/oauth/consent'
    | '/oauth/device'
    | '/$owner/'
    | '/$owner/agents/$agentId'
    | '/$owner/connectors/$connectorKey'
    | '/$owner/events/$eventId'
    | '/$owner/members/$userId'
    | '/$owner/watchers/$watcherId'
    | '/$owner/$entityType/'
    | '/$owner/agents/'
    | '/$owner/connectors/'
    | '/$owner/events/'
    | '/$owner/members/'
    | '/$owner/watchers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$owner/$'
    | '/account/settings'
    | '/auth/$pathname'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/oauth/consent'
    | '/oauth/device'
    | '/$owner'
    | '/$owner/agents/$agentId'
    | '/$owner/connectors/$connectorKey'
    | '/$owner/events/$eventId'
    | '/$owner/members/$userId'
    | '/$owner/watchers/$watcherId'
    | '/$owner/$entityType'
    | '/$owner/agents'
    | '/$owner/connectors'
    | '/$owner/events'
    | '/$owner/members'
    | '/$owner/watchers'
  id:
    | '__root__'
    | '/'
    | '/$owner/$'
    | '/$owner/agents'
    | '/account/settings'
    | '/auth/$pathname'
    | '/auth/accept-invitation'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/oauth/consent'
    | '/oauth/device'
    | '/$owner/'
    | '/$owner/agents/$agentId'
    | '/$owner/connectors/$connectorKey'
    | '/$owner/events/$eventId'
    | '/$owner/members/$userId'
    | '/$owner/watchers/$watcherId'
    | '/$owner/$entityType/'
    | '/$owner/agents/'
    | '/$owner/connectors/'
    | '/$owner/events/'
    | '/$owner/members/'
    | '/$owner/watchers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerSplatRoute: typeof OwnerSplatRoute
  OwnerAgentsRoute: typeof OwnerAgentsRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  AuthAcceptInvitationRoute: typeof AuthAcceptInvitationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthDeviceRoute: typeof OauthDeviceRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerConnectorsConnectorKeyRoute: typeof OwnerConnectorsConnectorKeyRoute
  OwnerEventsEventIdRoute: typeof OwnerEventsEventIdRoute
  OwnerMembersUserIdRoute: typeof OwnerMembersUserIdRoute
  OwnerWatchersWatcherIdRoute: typeof OwnerWatchersWatcherIdRoute
  OwnerEntityTypeIndexRoute: typeof OwnerEntityTypeIndexRoute
  OwnerConnectorsIndexRoute: typeof OwnerConnectorsIndexRoute
  OwnerEventsIndexRoute: typeof OwnerEventsIndexRoute
  OwnerMembersIndexRoute: typeof OwnerMembersIndexRoute
  OwnerWatchersIndexRoute: typeof OwnerWatchersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/device': {
      id: '/oauth/device'
      path: '/oauth/device'
      fullPath: '/oauth/device'
      preLoaderRoute: typeof OauthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invitation': {
      id: '/auth/accept-invitation'
      path: '/auth/accept-invitation'
      fullPath: '/auth/accept-invitation'
      preLoaderRoute: typeof AuthAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/agents': {
      id: '/$owner/agents'
      path: '/$owner/agents'
      fullPath: '/$owner/agents'
      preLoaderRoute: typeof OwnerAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$': {
      id: '/$owner/$'
      path: '/$owner/$'
      fullPath: '/$owner/$'
      preLoaderRoute: typeof OwnerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/watchers/': {
      id: '/$owner/watchers/'
      path: '/$owner/watchers'
      fullPath: '/$owner/watchers/'
      preLoaderRoute: typeof OwnerWatchersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/members/': {
      id: '/$owner/members/'
      path: '/$owner/members'
      fullPath: '/$owner/members/'
      preLoaderRoute: typeof OwnerMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/events/': {
      id: '/$owner/events/'
      path: '/$owner/events'
      fullPath: '/$owner/events/'
      preLoaderRoute: typeof OwnerEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/connectors/': {
      id: '/$owner/connectors/'
      path: '/$owner/connectors'
      fullPath: '/$owner/connectors/'
      preLoaderRoute: typeof OwnerConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/agents/': {
      id: '/$owner/agents/'
      path: '/'
      fullPath: '/$owner/agents/'
      preLoaderRoute: typeof OwnerAgentsIndexRouteImport
      parentRoute: typeof OwnerAgentsRoute
    }
    '/$owner/$entityType/': {
      id: '/$owner/$entityType/'
      path: '/$owner/$entityType'
      fullPath: '/$owner/$entityType/'
      preLoaderRoute: typeof OwnerEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/watchers/$watcherId': {
      id: '/$owner/watchers/$watcherId'
      path: '/$owner/watchers/$watcherId'
      fullPath: '/$owner/watchers/$watcherId'
      preLoaderRoute: typeof OwnerWatchersWatcherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/members/$userId': {
      id: '/$owner/members/$userId'
      path: '/$owner/members/$userId'
      fullPath: '/$owner/members/$userId'
      preLoaderRoute: typeof OwnerMembersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/events/$eventId': {
      id: '/$owner/events/$eventId'
      path: '/$owner/events/$eventId'
      fullPath: '/$owner/events/$eventId'
      preLoaderRoute: typeof OwnerEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/connectors/$connectorKey': {
      id: '/$owner/connectors/$connectorKey'
      path: '/$owner/connectors/$connectorKey'
      fullPath: '/$owner/connectors/$connectorKey'
      preLoaderRoute: typeof OwnerConnectorsConnectorKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/agents/$agentId': {
      id: '/$owner/agents/$agentId'
      path: '/$agentId'
      fullPath: '/$owner/agents/$agentId'
      preLoaderRoute: typeof OwnerAgentsAgentIdRouteImport
      parentRoute: typeof OwnerAgentsRoute
    }
  }
}

interface OwnerAgentsRouteChildren {
  OwnerAgentsAgentIdRoute: typeof OwnerAgentsAgentIdRoute
  OwnerAgentsIndexRoute: typeof OwnerAgentsIndexRoute
}

const OwnerAgentsRouteChildren: OwnerAgentsRouteChildren = {
  OwnerAgentsAgentIdRoute: OwnerAgentsAgentIdRoute,
  OwnerAgentsIndexRoute: OwnerAgentsIndexRoute,
}

const OwnerAgentsRouteWithChildren = OwnerAgentsRoute._addFileChildren(
  OwnerAgentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerSplatRoute: OwnerSplatRoute,
  OwnerAgentsRoute: OwnerAgentsRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  AuthAcceptInvitationRoute: AuthAcceptInvitationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthDeviceRoute: OauthDeviceRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerConnectorsConnectorKeyRoute: OwnerConnectorsConnectorKeyRoute,
  OwnerEventsEventIdRoute: OwnerEventsEventIdRoute,
  OwnerMembersUserIdRoute: OwnerMembersUserIdRoute,
  OwnerWatchersWatcherIdRoute: OwnerWatchersWatcherIdRoute,
  OwnerEntityTypeIndexRoute: OwnerEntityTypeIndexRoute,
  OwnerConnectorsIndexRoute: OwnerConnectorsIndexRoute,
  OwnerEventsIndexRoute: OwnerEventsIndexRoute,
  OwnerMembersIndexRoute: OwnerMembersIndexRoute,
  OwnerWatchersIndexRoute: OwnerWatchersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
