import type {Env} from '@lobu/connector-sdk';
export const COURSE_MEMORY_RETRIEVAL_TIMEOUT_MS=800;
const MAX_HITS=8,MAX_SEARCH_ROWS=64,MAX_TASK_CHARS=560,MAX_SKILL_TERMS=2,MAX_TITLE_CHARS=200,MAX_SNIPPET_CHARS=300,MAX_SOURCE_URL_CHARS=256,MAX_RETRIEVAL_JSON_CHARS=8000;
interface SearchRow{id:number;payload_text:string;title:string|null;source_url:string|null;organization_id:string;metadata:Record<string,unknown>}
export interface CourseMemoryRetrieval{status:'loaded'|'empty'|'degraded'|'invariant_violation';crossCourseGuard:'passed'|'failed';eventIds:number[];evidenceRefs:string[];snippets:Array<{eventId:number;title:string|null;text:string;sourceUrl:string|null}>}
export interface CourseMemoryRetrievalInput{organizationId:string;ownerUserId:string;agentId:string;courseEntityId:string;task:string;skillTerms?:string[];limit?:number;env?:Env}
export type CourseMemorySearch=(input:{organizationId:string;ownerUserId:string;agentId:string;entityIds:string[];query:string;limit:number;env?:Env;signal?:AbortSignal})=>Promise<unknown>;
export function buildCourseMemoryQuery(task:string,skillTerms:string[]=[]):string{const terms=[...new Set(skillTerms.map((term)=>term.trim()).filter(Boolean))].slice(0,MAX_SKILL_TERMS);return [task.trim().slice(0,MAX_TASK_CHARS),...terms].filter(Boolean).join(' ').slice(0,700)}
export function buildCourseMemoryQueries(task:string,skillTerms:string[]=[]):string[]{const bounded=task.trim().replace(/[，。！？!?]+$/u,'').slice(0,MAX_TASK_CHARS);const terms=[...new Set(skillTerms.map((term)=>term.trim()).filter(Boolean))].slice(0,MAX_SKILL_TERMS);const han=[...bounded].filter((char)=>/\p{Script=Han}/u.test(char)).join('');return [...new Set([bounded,...terms.filter((term)=>bounded.includes(term)),han.slice(-2),han.slice(-4),...terms])].filter((value)=>value.length>=2).slice(0,3)}
function parseRows(value:unknown):SearchRow[]|null{if(!Array.isArray(value)||value.length>MAX_SEARCH_ROWS)return null;const rows:SearchRow[]=[];for(const item of value){if(!item||typeof item!=='object')return null;const row=item as Record<string,unknown>;if(!Number.isSafeInteger(row.id)||Number(row.id)<=0||typeof row.payload_text!=='string'||row.payload_text.length>200_000||typeof row.organization_id!=='string'||!row.metadata||typeof row.metadata!=='object'||Array.isArray(row.metadata))return null;if(row.title!==null&&typeof row.title!=='string')return null;if(row.source_url!==null&&typeof row.source_url!=='string')return null;rows.push(row as unknown as SearchRow)}return rows}
function exactCourseIds(metadata:Record<string,unknown>):string[]{const value=metadata.course_entity_ids;return Array.isArray(value)&&value.length===1&&typeof value[0]==='string'?value:[]}
const clean=(value:string,max:number)=>value.replace(/[\u0000-\u001f\u007f\u2028\u2029]/gu,' ').slice(0,max);
function safeSourceUrl(value:string|null):string|null{if(!value)return null;try{const url=new URL(value);if(url.protocol!=='https:'&&url.protocol!=='http:')return null;url.username='';url.password='';url.search='';url.hash='';return clean(url.toString(),MAX_SOURCE_URL_CHARS)}catch{return null}}
function boundResult(result:CourseMemoryRetrieval):CourseMemoryRetrieval{for(let index=result.snippets.length-1;JSON.stringify(result).length>MAX_RETRIEVAL_JSON_CHARS&&index>=0;index--){const item=result.snippets[index];if(!item)continue;item.text=item.text.slice(0,100);item.title=item.title?.slice(0,80)??null;item.sourceUrl=null}for(let index=result.snippets.length-1;JSON.stringify(result).length>MAX_RETRIEVAL_JSON_CHARS&&index>=0;index--){const item=result.snippets[index];if(!item)continue;item.text='';item.title=null}return result}
export async function retrieveCourseMemory(input:CourseMemoryRetrievalInput,deps:{search:CourseMemorySearch;timeoutMs?:number}):Promise<CourseMemoryRetrieval>{const empty=(status:'empty'|'degraded'|'invariant_violation',guard:'passed'|'failed'='passed'):CourseMemoryRetrieval=>({status,crossCourseGuard:guard,eventIds:[],evidenceRefs:[],snippets:[]});const limit=typeof input.limit==='number'&&Number.isSafeInteger(input.limit)?Math.min(MAX_HITS,Math.max(1,input.limit)):MAX_HITS;let timeoutId:ReturnType<typeof setTimeout>|undefined;const controller=new AbortController();try{const run=async()=>{const merged:SearchRow[]=[];const seen=new Set<number>();for(const query of buildCourseMemoryQueries(input.task,input.skillTerms)){if(controller.signal.aborted)throw new Error('course memory aborted');const rows=parseRows(await deps.search({organizationId:input.organizationId,ownerUserId:input.ownerUserId,agentId:input.agentId,entityIds:[input.courseEntityId],query,limit,env:input.env,signal:controller.signal}));if(controller.signal.aborted)throw new Error('course memory aborted');if(!rows)throw new Error('invalid course memory response');for(const row of rows)if(!seen.has(row.id)){seen.add(row.id);merged.push(row)}if(merged.length>=limit)break}return merged};const timeout=new Promise<never>((_,reject)=>{timeoutId=setTimeout(()=>{controller.abort();reject(new Error('course memory timeout'))},deps.timeoutMs??COURSE_MEMORY_RETRIEVAL_TIMEOUT_MS)});const rows=await Promise.race([run(),timeout]);const scoped=rows.filter((row)=>typeof row.metadata.owner_user_id==='string'&&typeof row.metadata.agent_id==='string'&&Array.isArray(row.metadata.course_entity_ids));const mismatch=scoped.some((row)=>row.organization_id!==input.organizationId||row.metadata.owner_user_id!==input.ownerUserId||row.metadata.agent_id!==input.agentId||exactCourseIds(row.metadata)[0]!==input.courseEntityId);if(mismatch)return empty('invariant_violation','failed');const safe=scoped.slice(0,limit);if(safe.length===0)return empty('empty');return boundResult({status:'loaded',crossCourseGuard:'passed',eventIds:safe.map((row)=>row.id),evidenceRefs:safe.map((row)=>`lobu:event:${row.id}`),snippets:safe.map((row)=>({eventId:row.id,title:row.title===null?null:clean(row.title,MAX_TITLE_CHARS),text:clean(row.payload_text,MAX_SNIPPET_CHARS),sourceUrl:safeSourceUrl(row.source_url)}))})}catch{return empty('degraded')}finally{if(timeoutId)clearTimeout(timeoutId);controller.abort()}}
