import {describe,expect,test,vi} from 'vitest';
import {searchContentBySingleQuery} from '../search-path';
import {generateEmbeddings} from '../../embeddings';
const options={organization_id:'org',limit:8,sort_by:'score' as const,statement_timeout_ms:750};
function db(fail:boolean){const calls:string[]=[];const tx={unsafe:vi.fn(async(sql:string)=>{calls.push(sql);if(!sql.startsWith('SET LOCAL')&&fail)throw new Error('statement timeout');return[]})};return{calls,sql:{begin:vi.fn(async(fn:any)=>fn(tx)),unsafe:vi.fn()} as any};}
describe('explicit content search timeout',()=>{
 test('wraps embedding-outage direct text search in SET LOCAL and rethrows failure',async()=>{const fake=db(true);await expect(searchContentBySingleQuery(fake.sql,'受眾',options)).rejects.toThrow('statement timeout');expect(fake.calls[0]).toBe('SET LOCAL statement_timeout = 750');});
 test('wraps explicit embedding candidate search and rethrows failure',async()=>{const fake=db(true);await expect(searchContentBySingleQuery(fake.sql,'audience',{...options,query_embedding:[1],approximate_candidate_search:true})).rejects.toThrow('statement timeout');expect(fake.calls[0]).toBe('SET LOCAL statement_timeout = 750');});
 test('preserves implicit candidate timeout fail-open behavior',async()=>{const fake=db(true);await expect(searchContentBySingleQuery(fake.sql,'audience',{organization_id:'org',limit:8,sort_by:'score',query_embedding:[1],approximate_candidate_search:true})).resolves.toMatchObject({content:[]});expect(fake.calls[0]).toContain('SET LOCAL statement_timeout');});
 test('propagates the retrieval abort signal to embedding fetch',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockImplementation((_url,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new Error('aborted')),{once:true})));const controller=new AbortController();const pending=generateEmbeddings(['受眾'],{EMBEDDINGS_SERVICE_URL:'https://embed.test'} as never,controller.signal);controller.abort();await expect(pending).rejects.toThrow();expect(fetcher.mock.calls[0]?.[1]?.signal?.aborted).toBe(true);fetcher.mockRestore();});
 test('an aborted embedding search rejects before any SQL execution',async()=>{const fake=db(false);const controller=new AbortController();controller.abort();await expect(searchContentBySingleQuery(fake.sql,'audience',{...options,abort_signal:controller.signal},{EMBEDDINGS_SERVICE_URL:'https://embed.test'} as never)).rejects.toThrow();expect(fake.sql.begin).not.toHaveBeenCalled();expect(fake.sql.unsafe).not.toHaveBeenCalled();});
 test('a normal embedding service failure still falls back to text SQL',async()=>{const fetcher=vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('service down'));const fake=db(false);await expect(searchContentBySingleQuery(fake.sql,'audience',options,{EMBEDDINGS_SERVICE_URL:'https://embed.test'} as never)).resolves.toMatchObject({content:[]});expect(fake.sql.begin).toHaveBeenCalledTimes(1);fetcher.mockRestore();});
});
