import {describe,expect,test,vi} from 'vitest';
import {buildCourseMemoryQuery,retrieveCourseMemory} from '../orchestration/course-memory-retriever.js';
const base={organizationId:'org-1',ownerUserId:'user-1',agentId:'agent-1',courseEntityId:'course:user-1:a',task:'請整理這門課的招生策略',skillTerms:['受眾','夢想結果','Key Learning']};
const hit=(id:number,overrides:Record<string,unknown>={})=>({id,payload_text:`memory ${id}`,title:`title ${id}`,source_url:null,organization_id:'org-1',metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a']},...overrides});
describe('course memory retriever',()=>{
 test('builds a bounded task-derived query with bounded skill terms',()=>{const query=buildCourseMemoryQuery('x'.repeat(1000),['受眾','夢想結果','課程承諾','Key Learning','方法機制','案例','證據','Offer','extra']);expect(query.length).toBeLessThanOrEqual(700);expect(query).toContain('受眾');expect(query).toContain('Offer');expect(query).not.toContain('extra');});
 test('loads at most eight strictly scoped safe hits',async()=>{const search=vi.fn().mockResolvedValue(Array.from({length:10},(_,i)=>hit(i+1)));const result=await retrieveCourseMemory(base,{search});expect(search).toHaveBeenCalledWith(expect.objectContaining({agentId:'agent-1',entityIds:['course:user-1:a'],limit:8}));expect(result).toMatchObject({status:'loaded',crossCourseGuard:'passed',eventIds:[1,2,3,4,5,6,7,8]});expect(result.snippets).toHaveLength(8);});
 test('reports a successful empty search as loaded',async()=>{await expect(retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([])})).resolves.toMatchObject({status:'loaded',eventIds:[]});});
 test('excludes mismatched hits and marks a safe remainder partial',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([hit(1),hit(2,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:b']}}),hit(3,{organization_id:'other'}),hit(4,{metadata:{owner_user_id:'user-1',agent_id:'other',course_entity_ids:['course:user-1:a']}})])});expect(result).toMatchObject({status:'partial',crossCourseGuard:'failed',eventIds:[1]});});
 test('injects nothing when all hits mismatch',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([hit(2,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:b']}})])});expect(result).toMatchObject({status:'failed',crossCourseGuard:'failed',eventIds:[],snippets:[]});});
 test('fails open with no injected memory on infrastructure or malformed response',async()=>{await expect(retrieveCourseMemory(base,{search:vi.fn().mockRejectedValue(new Error('down'))})).resolves.toMatchObject({status:'failed',eventIds:[]});await expect(retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([{id:'bad'}])})).resolves.toMatchObject({status:'failed',eventIds:[]});});
});
