import {describe,expect,test,vi} from 'vitest';
import {buildCourseMemoryQueries,buildCourseMemoryQuery,retrieveCourseMemory} from '../orchestration/course-memory-retriever.js';
import {COURSE_MEMORY_STATEMENT_TIMEOUT_MS} from '../orchestration/course-memory-search.js';
import {buildCourseMemorySearchEnv} from '../orchestration/message-consumer.js';
const base={organizationId:'org-1',ownerUserId:'user-1',agentId:'agent-1',courseEntityId:'course:user-1:a',task:'請整理這門課的招生策略',skillTerms:['受眾','夢想結果','Key Learning']};
const hit=(id:number,overrides:Record<string,unknown>={})=>({id,payload_text:`memory ${id}`,title:`title ${id}`,source_url:null,organization_id:'org-1',metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a']},...overrides});
describe('course memory retriever',()=>{
 test('keeps the PostgreSQL timeout inside the 800ms gate budget',()=>expect(COURSE_MEMORY_STATEMENT_TIMEOUT_MS).toBeLessThan(800));
 test('builds production search env from the gateway process environment',()=>expect(buildCourseMemorySearchEnv({EMBEDDINGS_SERVICE_URL:'https://embed.runtime',EMBEDDINGS_SERVICE_TOKEN:'token'} as NodeJS.ProcessEnv)).toMatchObject({EMBEDDINGS_SERVICE_URL:'https://embed.runtime',EMBEDDINGS_SERVICE_TOKEN:'token'}));
 test('builds a bounded task-derived query with the two validated skill terms',()=>{const query=buildCourseMemoryQuery('x'.repeat(1000),['Key Learning','Offer']);expect(query.length).toBeLessThanOrEqual(700);expect(query).toContain('Key Learning');expect(query).toContain('Offer');});
 test('counts provider over-limit rows as dropped truncation',async()=>{const search=vi.fn().mockResolvedValue(Array.from({length:10},(_,i)=>hit(i+1)));const result=await retrieveCourseMemory(base,{search});expect(search).toHaveBeenCalledWith(expect.objectContaining({agentId:'agent-1',entityIds:['course:user-1:a'],limit:8}));expect(result).toMatchObject({status:'loaded',crossCourseGuard:'passed',candidateCount:10,safeCount:8,droppedCount:2,eventIds:[1,2,3,4,5,6,7,8]});expect(result.snippets).toHaveLength(8);});
 test('honors a declared retrieval limit while enforcing the global cap',async()=>{const search=vi.fn().mockResolvedValue(Array.from({length:10},(_,i)=>hit(i+1)));const result=await retrieveCourseMemory({...base,limit:3},{search});expect(search).toHaveBeenCalledWith(expect.objectContaining({limit:3}));expect(result.snippets).toHaveLength(3);const capped=vi.fn().mockResolvedValue(Array.from({length:10},(_,i)=>hit(i+1)));await retrieveCourseMemory({...base,limit:99},{search:capped});expect(capped).toHaveBeenCalledWith(expect.objectContaining({limit:8}));});
 test('reports a successful empty exact search as empty',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([])});expect(result).toMatchObject({status:'empty',crossCourseGuard:'passed',candidateCount:0,safeCount:0,droppedCount:0,eventIds:[],snippets:[]});expect(JSON.stringify(result)).not.toContain('memory ');});
 test.each([
  ['owner',hit(2,{payload_text:'UNSAFE_OWNER',metadata:{owner_user_id:'user-2',agent_id:'agent-1',course_entity_ids:['course:user-1:a']}})],
  ['agent',hit(2,{payload_text:'UNSAFE_AGENT',metadata:{owner_user_id:'user-1',agent_id:'agent-2',course_entity_ids:['course:user-1:a']}})],
  ['course',hit(2,{payload_text:'UNSAFE_COURSE',metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:b']}})],
  ['organization',hit(2,{payload_text:'UNSAFE_ORG',organization_id:'org-2'})],
 ])('fails the guard and excludes text for a %s mismatch',async(_name,row)=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([row])});expect(result).toMatchObject({status:'invariant_violation',crossCourseGuard:'failed',eventIds:[],snippets:[],candidateCount:1,safeCount:0,droppedCount:1});expect(JSON.stringify(result)).not.toContain('UNSAFE_');});
 test('rejects mixed safe and unsafe candidates as one invariant violation',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([hit(1,{payload_text:'SAFE_TEXT'}),hit(2,{payload_text:'UNSAFE_MIXED',metadata:{owner_user_id:'other',agent_id:'agent-1',course_entity_ids:['course:user-1:a']}})])});expect(result).toMatchObject({status:'invariant_violation',crossCourseGuard:'failed',eventIds:[],snippets:[],candidateCount:2,safeCount:1,droppedCount:1});expect(JSON.stringify(result)).not.toContain('SAFE_TEXT');expect(JSON.stringify(result)).not.toContain('UNSAFE_MIXED');});
 test.each([
  ['missing owner',hit(3,{payload_text:'UNSAFE_HYDRATION_OWNER',metadata:{agent_id:'agent-1',course_entity_ids:['course:user-1:a']}})],
  ['missing agent',hit(3,{payload_text:'UNSAFE_HYDRATION_AGENT',metadata:{owner_user_id:'user-1',course_entity_ids:['course:user-1:a']}})],
  ['missing course',hit(3,{payload_text:'UNSAFE_HYDRATION_COURSE',metadata:{owner_user_id:'user-1',agent_id:'agent-1'}})],
 ])('treats %s as a hydration contract invariant violation',async(_name,row)=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([row])});expect(result).toMatchObject({status:'invariant_violation',crossCourseGuard:'failed',candidateCount:1,safeCount:0,droppedCount:1,eventIds:[],snippets:[]});expect(JSON.stringify(result)).not.toContain('UNSAFE_HYDRATION');});
 test('rejects every row when the dependency returns an identity mismatch',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([hit(1),hit(2,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:b']}})])});expect(result).toMatchObject({status:'invariant_violation',crossCourseGuard:'failed',eventIds:[],snippets:[]});});
 test('rejects a multi-course row instead of treating containment as exact scope',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([hit(1,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a','course:user-1:b']}})])});expect(result).toMatchObject({status:'invariant_violation',crossCourseGuard:'failed',eventIds:[],snippets:[]});});
 test('injects nothing when all hits mismatch',async()=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue([hit(2,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:b']}})])});expect(result).toMatchObject({status:'invariant_violation',crossCourseGuard:'failed',eventIds:[],snippets:[]});});
 test('degrades with no injected memory on infrastructure',async()=>{await expect(retrieveCourseMemory(base,{search:vi.fn().mockRejectedValue(new Error('down'))})).resolves.toMatchObject({status:'degraded',crossCourseGuard:'passed',candidateCount:0,safeCount:0,droppedCount:0,eventIds:[]});});
 test.each([
  ['non-array object',{rows:[hit(1)]},0],
  ['malformed row',[{id:'bad',payload_text:'UNSAFE_MALFORMED'}],1],
  ['mixed valid and malformed rows',[hit(1,{payload_text:'UNSAFE_VALID_NEIGHBOR'}),{id:'bad',payload_text:'UNSAFE_MALFORMED'}],2],
 ])('degrades malformed %s with safely countable received rows',async(_name,response,candidateCount)=>{const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue(response)});expect(result).toMatchObject({status:'degraded',crossCourseGuard:'passed',candidateCount,safeCount:0,droppedCount:candidateCount,eventIds:[],snippets:[]});expect(JSON.stringify(result)).not.toContain('UNSAFE_');});
 test('bounds titles, strips URL query secrets, and caps aggregate serialized retrieval',async()=>{const rows=Array.from({length:8},(_,i)=>hit(i+1,{title:'t'.repeat(5000),payload_text:'p'.repeat(200000),source_url:`https://example.com/path?token=secret-${i}#private`}));const result=await retrieveCourseMemory(base,{search:vi.fn().mockResolvedValue(rows)});expect(result.snippets).toHaveLength(8);expect(result.snippets.every((item)=>item.title?.length===200)).toBe(true);expect(result.snippets.every((item)=>item.sourceUrl==='https://example.com/path')).toBe(true);expect(JSON.stringify(result)).not.toContain('secret-');expect(JSON.stringify(result).length).toBeLessThanOrEqual(8000);});
 test('uses bounded Chinese fallback terms with skill enabled or disabled and dedupes hits',async()=>{expect(buildCourseMemoryQueries('請幫我整理這門課的受眾。',[])).toEqual(['請幫我整理這門課的受眾','受眾','課的受眾']);const search=vi.fn().mockImplementation(async({query})=>query==='受眾'?[hit(7)]:[]);const env={EMBEDDINGS_SERVICE_URL:'https://embeddings.test'} as never;const result=await retrieveCourseMemory({...base,task:'請幫我整理這門課的受眾。',skillTerms:['受眾'],env},{search});expect(result.eventIds).toEqual([7]);expect(search).toHaveBeenCalledTimes(3);expect(search).toHaveBeenCalledWith(expect.objectContaining({query:'受眾',env}));});
 test('executes task plus the two validated skill terms without truncation',()=>expect(buildCourseMemoryQueries('review now',['Key Learning','Offer'])).toEqual(['review now','Key Learning','Offer']));
 test('fails open within the named retrieval budget',async()=>{const started=Date.now();const result=await retrieveCourseMemory(base,{search:()=>new Promise(()=>{}),timeoutMs:10});expect(result).toMatchObject({status:'degraded',crossCourseGuard:'passed',candidateCount:0,safeCount:0,droppedCount:0,eventIds:[],snippets:[]});expect(JSON.stringify(result)).not.toContain(base.task);expect(Date.now()-started).toBeLessThan(200);});
 test('stops fallback queries after an explicit search timeout',async()=>{const search=vi.fn().mockRejectedValue(new Error('statement timeout'));const result=await retrieveCourseMemory(base,{search});expect(result.status).toBe('degraded');expect(search).toHaveBeenCalledTimes(1);});
 test('aborts a hung first query and never starts later queries after it resolves',async()=>{let release:()=>void=()=>{};const first=new Promise<void>((resolve)=>{release=resolve});const search=vi.fn(async()=>{await first;return[]});const resultPromise=retrieveCourseMemory(base,{search,timeoutMs:10});await new Promise((resolve)=>setTimeout(resolve,20));expect((await resultPromise).status).toBe('degraded');release();await new Promise((resolve)=>setTimeout(resolve,0));expect(search).toHaveBeenCalledTimes(1);expect(search.mock.calls[0]?.[0].signal.aborted).toBe(true);});
 test('dedupes by stable event id and source ref and carries bounded provenance without owner ids',async()=>{const search=vi.fn().mockResolvedValue([hit(1,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a'],source_ref:'drive:user-1:file-1'}}),hit(2,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a'],source_ref:'drive:user-1:file-1'}}),hit(3,{metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a'],source_ref:'drive:user-1:file-2',course_readiness:{audience:'課程 PM'}}})]);const result=await retrieveCourseMemory({...base,skillTerms:[]},{search});expect(result.eventIds).toEqual([1,3]);expect(result.snippets).toEqual([expect.objectContaining({eventId:1,sourceRef:expect.stringMatching(/^lobu:source:/),provenanceKind:'fresh_course_retrieval',readinessFields:{}}),expect.objectContaining({eventId:3,sourceRef:expect.stringMatching(/^lobu:source:/),provenanceKind:'fresh_course_retrieval',readinessFields:{audience:'課程 PM'}})]);expect(new Set(result.evidenceRefs).size).toBe(2);expect(JSON.stringify(result)).not.toContain('user-1');expect(JSON.stringify(result)).not.toContain('agent-1');});
 test('ignores free text and rejects unknown or non-string structured readiness values',async()=>{const result=await retrieveCourseMemory({...base,skillTerms:[]},{search:vi.fn().mockResolvedValue([hit(1,{payload_text:'audience: invented from prose',metadata:{owner_user_id:'user-1',agent_id:'agent-1',course_entity_ids:['course:user-1:a'],course_readiness:{audience:42,offer:'invented'}}})])});expect(result.snippets[0]?.readinessFields).toEqual({});});
});
