import { describe, expect, it, vi } from 'vitest';
import type { MessagePayload } from '@lobu/core';
import { attachCourseContextForReviewedScope } from '../orchestration/course-context-gate.js';
import { MessageConsumer, compareCourseContextIdentity, parseCourseContextRolloutConfig } from '../orchestration/message-consumer.js';

describe('course context tracer', () => {
  it.each([[undefined,undefined,'resolved_missing'],[{courseKey:'x',courseEntityId:'course:x'},undefined,'legacy_missing'],[{courseKey:'x',courseEntityId:'course:x'},{courseKey:'x',courseEntityId:'course:x'},'match'],[{courseKey:'x',courseEntityId:'course:x'},{courseKey:'y',courseEntityId:'course:y'},'mismatch']] as const)('compares canonical legacy identities %#',(resolved,legacy,want)=>expect(compareCourseContextIdentity(resolved,legacy)).toBe(want));
  it.each([
    [{status:'not_required'},404,'resolved_missing'],
    [{status:'context_unavailable',reasonCode:'bundle_unavailable',resolvedCourse:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},404,'legacy_missing'],
    [{status:'context_unavailable',reasonCode:'bundle_unavailable',resolvedCourse:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},200,'match'],
    [{status:'ready',context:{course:{courseKey:'y',courseEntityId:'course:y',displayName:'Y'},resolution:{confidence:'high',matchedBy:['single_course_default']},context:{contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'safe'},retrieval:{status:'failed',crossCourseGuard:'passed',eventIds:[],evidenceRefs:[],snippets:[]}}},200,'mismatch'],
  ] as const)('emits integrated legacy comparison %#',async(result,httpStatus,want)=>{const oldMode=process.env.COURSE_CONTEXT_GATE_MODE,oldUrl=process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL,oldSecret=process.env.TOOLBOX_INTERNAL_SECRET;process.env.COURSE_CONTEXT_GATE_MODE='shadow';process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL='https://toolbox.test/legacy';process.env.TOOLBOX_INTERNAL_SECRET='secret';const fetchSpy=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(httpStatus===200?JSON.stringify({courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'safe'}):'',{status:httpStatus}));const events:any[]=[];const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,vi.fn().mockResolvedValue(result as any),async event=>{events.push(event);});await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageId:'m',messageText:'secret',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(events.find(event=>event.event==='context.legacy.compared')?.comparison).toBe(want);}finally{fetchSpy.mockRestore();for(const[key,value]of [['COURSE_CONTEXT_GATE_MODE',oldMode],['COURSE_CONTEXT_LEGACY_COMPARE_URL',oldUrl],['TOOLBOX_INTERNAL_SECRET',oldSecret]] as const){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});
  it.each([
    [{}, { mode: 'enforce', legacyFallback: false }],
    [{ COURSE_CONTEXT_GATE_MODE: 'shadow', COURSE_CONTEXT_LEGACY_FALLBACK: 'true' }, { mode: 'shadow', legacyFallback: true }],
    [{ COURSE_CONTEXT_GATE_MODE: 'single_course', COURSE_CONTEXT_LEGACY_FALLBACK: 'TRUE' }, { mode: 'single_course', legacyFallback: true }],
    [{ COURSE_CONTEXT_GATE_MODE: 'enforce', COURSE_CONTEXT_LEGACY_FALLBACK: 'false' }, { mode: 'enforce', legacyFallback: false }],
    [{ COURSE_CONTEXT_GATE_MODE: 'typo', COURSE_CONTEXT_LEGACY_FALLBACK: 'yes' }, { mode: 'off', legacyFallback: false }],
  ])('parses narrow rollout config %#', (source, expected) => expect(parseCourseContextRolloutConfig(source)).toEqual(expected));

  it('off mode sends the legacy payload without invoking the course resolver', async () => {
    const resolver = vi.fn(); let forwarded: MessagePayload | undefined;
    const queue = { createQueue: vi.fn(), send: vi.fn(async (name: string, payload: MessagePayload) => { if (name.startsWith('thread_message_')) forwarded = payload; return 'job'; }) };
    const previous = process.env.COURSE_CONTEXT_GATE_MODE; process.env.COURSE_CONTEXT_GATE_MODE = 'off';
    try {
      const consumer = new MessageConsumer({ queues: { expireInSeconds: 1, retryLimit: 1 } } as never, {} as never, queue as never, resolver);
      const payload = { userId:'pm-1',agentId:'shifu-u-pm-1',conversationId:'conv-1',messageText:'course secret',platformMetadata:{courseScope:'reviewed'} } as MessagePayload;
      await (consumer as unknown as {dispatchCourseContextBoundary(p:MessagePayload,d:string):Promise<boolean>}).dispatchCourseContextBoundary(payload,'d');
      expect(resolver).not.toHaveBeenCalled(); expect(forwarded?.resolvedCourseContext).toBeUndefined();
    } finally { if(previous===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=previous; }
  });
  it.each(['off','shadow'])('%s strips a caller-prepopulated course context before dispatch',async(mode)=>{const resolver=vi.fn().mockResolvedValue({status:'not_required'});let forwarded:MessagePayload|undefined;const queue={createQueue:vi.fn(),send:vi.fn(async(name:string,payload:MessagePayload)=>{if(name.startsWith('thread_message_'))forwarded=payload;return'job';})};const old=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE=mode;try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);const payload:any={userId:'u',agentId:'a',conversationId:'c',messageId:'m',messageText:'提醒我繳電話費',platformMetadata:{},resolvedCourseContext:{trust:{ownerUserId:'u',agentId:'a',conversationId:'c',courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1},course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},resolution:{confidence:'high',matchedBy:['message_name']},context:{contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'fabricated'},retrieval:{status:'loaded',crossCourseGuard:'passed',eventIds:[],evidenceRefs:[],snippets:[]}}};await (consumer as any).dispatchCourseContextBoundary(payload,'d');expect(forwarded?.resolvedCourseContext).toBeUndefined();}finally{if(old===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=old;}});

  it('shadow mode observes resolution on a clone but never changes worker or terminal behavior', async () => {
    const resolver=vi.fn(async(actual:MessagePayload)=>{actual.resolvedCourseContext={course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},resolution:{confidence:'high',matchedBy:['single_course_default']},context:{contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'SECRET CONTEXT'},retrieval:{status:'failed',crossCourseGuard:'passed',eventIds:[],evidenceRefs:[],snippets:[]}};return {status:'clarification_required',candidates:[{courseKey:'x',displayName:'X'}]} as const;});
    let forwarded:MessagePayload|undefined; const queue={createQueue:vi.fn(),send:vi.fn(async(name:string,payload:MessagePayload)=>{if(name.startsWith('thread_message_'))forwarded=payload;return'job';})};
    const previous=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='shadow';
    try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);const payload={userId:'u',agentId:'a',conversationId:'c',messageText:'SECRET MESSAGE',platformMetadata:{courseScope:'reviewed'}} as MessagePayload;await (consumer as any).dispatchCourseContextBoundary(payload,'d');expect(resolver).toHaveBeenCalled();expect(forwarded?.resolvedCourseContext).toBeUndefined();expect(queue.send).not.toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());}finally{if(previous===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=previous;}
  });
  it('shadow mode dispatches the original payload when the resolver rejects',async()=>{const resolver=vi.fn().mockRejectedValue(new Error('down'));let forwarded:MessagePayload|undefined;const queue={createQueue:vi.fn(),send:vi.fn(async(name:string,payload:MessagePayload)=>{if(name.startsWith('thread_message_'))forwarded=payload;return'job';})};const previous=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='shadow';try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);const payload={userId:'u',agentId:'a',conversationId:'c',messageText:'ORIGINAL SECRET',platformMetadata:{courseScope:'reviewed'}} as MessagePayload;await (consumer as any).dispatchCourseContextBoundary(payload,'d');expect(forwarded?.messageText).toBe('ORIGINAL SECRET');expect(forwarded?.resolvedCourseContext).toBeUndefined();expect(queue.send).not.toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());}finally{if(previous===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=previous;}});
  it('single_course fails ambiguous course work closed',async()=>{const resolver=vi.fn().mockResolvedValue({status:'clarification_required',candidates:[{courseKey:'a',displayName:'A'},{courseKey:'b',displayName:'B'}]});const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const previous=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='single_course';try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageText:'course',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(queue.send).toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_message_d',expect.anything(),expect.anything());}finally{if(previous===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=previous;}});
  it.each(['resolver_unavailable','bundle_unavailable','bundle_identity_mismatch'])('single_course terminally blocks %s without naked worker dispatch',async(reasonCode)=>{const resolver=vi.fn().mockResolvedValue({status:'context_unavailable',reasonCode});const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const previous=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='single_course';try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageText:'課程工作',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(queue.send).toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_message_d',expect.anything(),expect.anything());}finally{if(previous===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=previous;}});
  it('single_course preserves a true non-course bypass',async()=>{const resolver=vi.fn().mockResolvedValue({status:'not_required'});const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const previous=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='single_course';try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageText:'提醒我繳電話費'} as MessagePayload,'d');expect(queue.send).toHaveBeenCalledWith('thread_message_d',expect.not.objectContaining({resolvedCourseContext:expect.anything()}),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());}finally{if(previous===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=previous;}});
  it('enforce keeps exact legacy comparison diagnostic-only',async()=>{const resolver=vi.fn().mockResolvedValue({status:'context_unavailable',reasonCode:'bundle_unavailable',resolvedCourse:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}});const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const oldMode=process.env.COURSE_CONTEXT_GATE_MODE,oldFallback=process.env.COURSE_CONTEXT_LEGACY_FALLBACK,oldUrl=process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL,oldSecret=process.env.TOOLBOX_INTERNAL_SECRET;process.env.COURSE_CONTEXT_GATE_MODE='enforce';process.env.COURSE_CONTEXT_LEGACY_FALLBACK='true';process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL='https://toolbox.test/legacy';process.env.TOOLBOX_INTERNAL_SECRET='secret';const fetchSpy=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'safe'})));try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageText:'course',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(queue.send).toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_message_d',expect.anything(),expect.anything());}finally{fetchSpy.mockRestore();for(const[key,value]of [['COURSE_CONTEXT_GATE_MODE',oldMode],['COURSE_CONTEXT_LEGACY_FALLBACK',oldFallback],['COURSE_CONTEXT_LEGACY_COMPARE_URL',oldUrl],['TOOLBOX_INTERNAL_SECRET',oldSecret]] as const){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});
  it('enforce never consults or injects legacy context for multi-course ambiguity',async()=>{const resolver=vi.fn().mockResolvedValue({status:'clarification_required',candidates:[{courseKey:'a',displayName:'A'},{courseKey:'b',displayName:'B'}]});const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const oldMode=process.env.COURSE_CONTEXT_GATE_MODE,oldFallback=process.env.COURSE_CONTEXT_LEGACY_FALLBACK,oldUrl=process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL,oldSecret=process.env.TOOLBOX_INTERNAL_SECRET;process.env.COURSE_CONTEXT_GATE_MODE='enforce';process.env.COURSE_CONTEXT_LEGACY_FALLBACK='true';process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL='https://toolbox.test/legacy';process.env.TOOLBOX_INTERNAL_SECRET='secret';const fetchSpy=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('',{status:404}));try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,resolver);await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageText:'course',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(fetchSpy).not.toHaveBeenCalled();expect(queue.send).toHaveBeenCalledWith('thread_response',expect.not.objectContaining({resolvedCourseContext:expect.anything()}),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_message_d',expect.anything(),expect.anything());}finally{fetchSpy.mockRestore();for(const[key,value]of [['COURSE_CONTEXT_GATE_MODE',oldMode],['COURSE_CONTEXT_LEGACY_FALLBACK',oldFallback],['COURSE_CONTEXT_LEGACY_COMPARE_URL',oldUrl],['TOOLBOX_INTERNAL_SECRET',oldSecret]] as const){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});
  it('uses the Toolbox resolver and bundle contract to attach bounded context', async () => {
    const fetcher = vi.fn()
      .mockResolvedValueOnce(new Response(JSON.stringify({ status: 'resolved', confidence: 'high', matchedBy: ['single_course_default'], course: { courseKey: 'super-ai', courseEntityId: 'course:pm-1:super-ai', displayName: '超級 AI 個體', aliases: ['超級AI'], status: 'active' } }), { status: 200 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ course: { courseKey: 'super-ai', courseEntityId: 'course:pm-1:super-ai', displayName: '超級 AI 個體', aliases: ['超級AI'], status: 'active' }, profile: { pmRole: null, teacher: null, collaborators: [], audience: null, coursePromise: null, resourceLocations: {} }, context: { agentMd: '已確認摘要', contextPackId: 'pack-super-ai', version: 1, confidence: 'high', generatedAt: '2026-07-11T00:00:00Z', lastIndexedAt: null, stale: false }, evidence: { confirmed: [], candidates: [] } }), { status: 200 }));
    const payload = { userId: 'pm-1', agentId: 'shifu-u-pm-1', conversationId: 'conv-1', messageText: '幫我想三個秘密', platformMetadata: { courseScope: 'reviewed' } } as MessagePayload;
    await attachCourseContextForReviewedScope(payload, { baseUrl: 'https://toolbox.test/agent-workbench/course-context', secret: 'secret', fetcher });
    expect(payload.resolvedCourseContext).toMatchObject({trust:{ownerUserId:'pm-1',agentId:'shifu-u-pm-1',conversationId:'conv-1',courseKey:'super-ai',courseEntityId:'course:pm-1:super-ai',contextPackId:'pack-super-ai',contextVersion:1},course:{courseKey:'super-ai'},context:{contextPackId:'pack-super-ai',contextVersion:1},retrieval:{crossCourseGuard:'passed'}});
  });

  it('emits ordered safe gate events without message, context body, or secret', async () => {
    const events: Array<Record<string, unknown>>=[];
    const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active'}}))).mockResolvedValueOnce(new Response(JSON.stringify({course:{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active'},profile:{pmRole:null,teacher:null,collaborators:[],audience:null,coursePromise:null,resourceLocations:{}},context:{agentMd:'SECRET CONTEXT',contextPackId:'p',version:2,confidence:'high',generatedAt:'2026-07-11T00:00:00Z',lastIndexedAt:null,stale:false},evidence:{confirmed:[],candidates:[]}})));
    const payload={userId:'owner-secret',agentId:'agent-key',conversationId:'conversation-secret',messageId:'m1',messageText:'SECRET MESSAGE',platformMetadata:{courseScope:'reviewed'}} as MessagePayload;
    await attachCourseContextForReviewedScope(payload,{baseUrl:'https://toolbox.test',secret:'TOKEN SECRET',fetcher,traceEmitter:async(event)=>{events.push(event);}});
    expect(events.map(event=>event.event)).toEqual(['context.gate.started','context.course.resolved','context.bundle.loaded','context.memory.degraded','context.guard.passed']);
    const serialized=JSON.stringify(events);expect(serialized).not.toContain('SECRET MESSAGE');expect(serialized).not.toContain('SECRET CONTEXT');expect(serialized).not.toContain('TOKEN SECRET');expect(serialized).not.toContain('owner-secret');expect(serialized).not.toContain('conversation-secret');
  });

  it('enriches the actual MessageConsumer dispatch payload in resolve-arm-send order', async () => {
    let createCount = 0;
    const queue = { createQueue: async () => { order.push(createCount++ === 0 ? 'arm' : 'create-send'); }, send: async (name: string, actual: MessagePayload) => { if (name.startsWith('thread_message_')) { order.push('send'); forwarded = actual; } return 'job'; } };
    const consumer = new MessageConsumer({ queues: { expireInSeconds: 1, retryLimit: 1 } } as never, {} as never, queue as never, async (actual) => { order.push('resolve'); actual.resolvedCourseContext = { trust:{ownerUserId:'pm-1',agentId:'shifu-u-pm-1',conversationId:'conv-1',courseKey:'super-ai',courseEntityId:'course:pm-1:super-ai',contextPackId:'pack-super-ai',contextVersion:1},course: { courseKey: 'super-ai', courseEntityId: 'course:pm-1:super-ai', displayName: '超級 AI 個體' }, resolution: { confidence: 'high', matchedBy: ['single_course_default'] }, context: { contextPackId: 'pack-super-ai', contextVersion: 1, stale: false, confirmedSummary: '已確認摘要' }, retrieval: { status: 'failed',crossCourseGuard:'passed', eventIds: [], evidenceRefs: [],snippets:[] } }; });
    const order: string[] = [];
    let forwarded: MessagePayload | undefined;
    const payload = { userId: 'pm-1', agentId: 'shifu-u-pm-1', conversationId: 'conv-1', messageText: 'x', platformMetadata: { courseScope: 'reviewed' } } as MessagePayload;
    await (consumer as unknown as { dispatchCourseContextBoundary(p: MessagePayload, d: string): Promise<void> }).dispatchCourseContextBoundary(payload, 'test-deployment');
    expect(order).toEqual(['resolve', 'arm', 'create-send', 'send']);
    expect(forwarded?.resolvedCourseContext?.course.courseKey).toBe('super-ai');
  });

  it.each([
    ['malformed json', [new Response('{', { status: 200 })]],
    ['wrong resolve shape', [new Response(JSON.stringify({ status: 'resolved' }), { status: 200 })]],
    ['string false', [new Response(JSON.stringify({ status: 'resolved', confidence: 'high', matchedBy: ['single_course_default'], course: { courseKey: 'super-ai', courseEntityId: 'course:1', displayName: 'AI' } })), new Response(JSON.stringify({ course: { courseKey: 'super-ai', courseEntityId: 'course:1', displayName: 'AI' }, context: { contextPackId: 'p', version: 1, stale: 'false', confirmedSummary: 'ok' } }))]],
    ['invalid version', [new Response(JSON.stringify({ status: 'resolved', confidence: 'high', matchedBy: ['single_course_default'], course: { courseKey: 'super-ai', courseEntityId: 'course:1', displayName: 'AI' } })), new Response(JSON.stringify({ course: { courseKey: 'super-ai', courseEntityId: 'course:1', displayName: 'AI' }, context: { contextPackId: 'p', version: 0, stale: false, confirmedSummary: 'ok' } }))]],
    ['oversized summary', [new Response(JSON.stringify({ status: 'resolved', confidence: 'high', matchedBy: ['single_course_default'], course: { courseKey: 'super-ai', courseEntityId: 'course:1', displayName: 'AI' } })), new Response(JSON.stringify({ course: { courseKey: 'super-ai', courseEntityId: 'course:1', displayName: 'AI' }, context: { contextPackId: 'p', version: 1, stale: false, confirmedSummary: 'x'.repeat(8001) } }))]],
  ])('terminalizes %s without attaching context', async (_name, responses) => {
    const fetcher = vi.fn(); for (const response of responses) fetcher.mockResolvedValueOnce(response);
    const payload = { userId: 'pm-1', agentId: 'shifu-u-pm-1', conversationId: 'conv-1', messageText: 'x', platformMetadata: { courseScope: 'reviewed' } } as MessagePayload;
    await expect(attachCourseContextForReviewedScope(payload, { baseUrl: 'https://toolbox.test', secret: 'secret', fetcher })).resolves.toMatchObject({ status: 'context_unavailable' });
    expect(payload.resolvedCourseContext).toBeUndefined();
  });
  it.each([['rejecting',async()=>{throw new Error('obs down');}],['never',async()=>new Promise<void>(()=>{})]] as const)('shadow fails open for a %s injected emitter',async(_name,emitter)=>{const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const oldMode=process.env.COURSE_CONTEXT_GATE_MODE,oldUrl=process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL;process.env.COURSE_CONTEXT_GATE_MODE='shadow';delete process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL;try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,vi.fn().mockRejectedValue(new Error('resolver down')),emitter);const started=Date.now();await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageId:'m',messageText:'ORIGINAL',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(Date.now()-started).toBeLessThan(150);expect(queue.send).toHaveBeenCalledWith('thread_message_d',expect.objectContaining({messageText:'ORIGINAL'}),expect.anything());}finally{if(oldMode===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=oldMode;if(oldUrl===undefined)delete process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL;else process.env.COURSE_CONTEXT_LEGACY_COMPARE_URL=oldUrl;}});
  it.each([['missing',undefined],['owner mismatch',{ownerUserId:'other',agentId:'a',conversationId:'c',courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1}],['agent mismatch',{ownerUserId:'u',agentId:'other',conversationId:'c',courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1}],['conversation mismatch',{ownerUserId:'u',agentId:'a',conversationId:'other',courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1}],['course mismatch',{ownerUserId:'u',agentId:'a',conversationId:'c',courseKey:'y',courseEntityId:'course:y',contextPackId:'p',contextVersion:1}],['bundle mismatch',{ownerUserId:'u',agentId:'a',conversationId:'c',courseKey:'x',courseEntityId:'course:x',contextPackId:'other',contextVersion:2}]])('enforce terminally blocks ready context with %s trust',async(_name,trust)=>{const context:any={trust,course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},resolution:{confidence:'high',matchedBy:['message_name']},context:{contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'safe'},retrieval:{status:'loaded',crossCourseGuard:'passed',eventIds:[],evidenceRefs:[],snippets:[]}};const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const oldMode=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='enforce';try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,vi.fn().mockResolvedValue({status:'ready',context}));await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageId:'m',messageText:'三個秘密',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(queue.send).toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_message_d',expect.anything(),expect.anything());}finally{if(oldMode===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=oldMode;}});
  it('enforce terminally blocks a failed cross-course guard',async()=>{const context:any={trust:{ownerUserId:'u',agentId:'a',conversationId:'c',courseKey:'x',courseEntityId:'course:x',contextPackId:'p',contextVersion:1},course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},resolution:{confidence:'high',matchedBy:['message_name']},context:{contextPackId:'p',contextVersion:1,stale:false,confirmedSummary:'safe'},retrieval:{status:'partial',crossCourseGuard:'failed',eventIds:[],evidenceRefs:[],snippets:[]}};const queue={createQueue:vi.fn(),send:vi.fn().mockResolvedValue('job')};const oldMode=process.env.COURSE_CONTEXT_GATE_MODE;process.env.COURSE_CONTEXT_GATE_MODE='enforce';try{const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{} as never,queue as never,vi.fn().mockResolvedValue({status:'ready',context}));await (consumer as any).dispatchCourseContextBoundary({userId:'u',agentId:'a',conversationId:'c',messageId:'m',messageText:'三個秘密',platformMetadata:{courseScope:'reviewed'}} as MessagePayload,'d');expect(queue.send).toHaveBeenCalledWith('thread_response',expect.anything(),expect.anything());expect(queue.send).not.toHaveBeenCalledWith('thread_message_d',expect.anything(),expect.anything());}finally{if(oldMode===undefined)delete process.env.COURSE_CONTEXT_GATE_MODE;else process.env.COURSE_CONTEXT_GATE_MODE=oldMode;}});
});
