import type { MessagePayload } from '@lobu/core';
import { describe, expect, test, vi } from 'vitest';
import { attachCourseContextForReviewedScope, requiresCourseContext } from '../orchestration/course-context-gate.js';
const payload = (messageText:string, platformMetadata:Record<string,unknown>={}):MessagePayload => ({userId:'u',agentId:'a',conversationId:'c',channelId:'ch',messageId:'m',platform:'line',messageText,platformMetadata,agentOptions:{}} as MessagePayload);
const candidate = {courseKey:'b',courseEntityId:'course:b',displayName:'B 課',aliases:['B'],status:'active',reasons:['message_alias']};
describe('course context gate', () => {
  test('scheduled course A overrides conversation binding B without persisting A',async()=>{
    const data=payload('準備排程課程任務');
    data.scheduledCourseContext={schemaVersion:1,source:'calendar_scheduled_wake',automationId:'auto-1',jobId:'job-1',runId:42,taskKind:'opp_coach_rehearsal_prompt',course:{ownerUserId:'u',agentId:'a',courseKey:'a',courseEntityId:'course:a',displayName:'A 課'},evidenceReadiness:'canonical_only'};
    const manager={getSessionStrict:vi.fn().mockResolvedValue({shifuCourseContext:{courseKey:'b',courseEntityId:'course:b'}}),bindActiveCourse:vi.fn()};
    const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({status:'resolved',confidence:'high',matchedBy:['explicit_course_key'],course:{courseKey:'a',courseEntityId:'course:a',displayName:'A 課'}}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('a')),{status:200}));
    const result=await attachCourseContextForReviewedScope(data,{baseUrl:'https://t',secret:'s',fetcher,sessionManager:manager as never,sessionKey:'session'});
    const request=JSON.parse((fetcher.mock.calls[0]?.[1] as RequestInit).body as string);
    expect(request).toMatchObject({explicitCourseKey:'a'});
    expect(request).not.toHaveProperty('boundCourseKey');
    expect(result).toMatchObject({status:'ready',context:{course:{courseKey:'a'}}});
    expect(manager.bindActiveCourse).not.toHaveBeenCalled();
  });
  test.each([
    ['schema',{schemaVersion:2}],
    ['owner',{course:{ownerUserId:'other'}}],
    ['agent',{course:{agentId:'other'}}],
  ])('invalid scheduled %s fails closed before Toolbox',async(_name,patch)=>{
    const data=payload('scheduled');
    const base:any={schemaVersion:1,source:'calendar_scheduled_wake',automationId:'auto',jobId:'job',runId:1,taskKind:'opp_coach_event_prompt',course:{ownerUserId:'u',agentId:'a',courseKey:'a',courseEntityId:'course:a',displayName:'A'},evidenceReadiness:'canonical_only'};
    data.scheduledCourseContext={...base,...patch,course:{...base.course,...((patch as any).course??{})}};
    const fetcher=vi.fn();
    await expect(attachCourseContextForReviewedScope(data,{baseUrl:'https://t',secret:'s',fetcher})).resolves.toEqual({status:'context_unavailable',reasonCode:'invalid_scheduled_course_context'});
    expect(fetcher).not.toHaveBeenCalled();
  });
  test.each([
    [{status:'missing',reason:'archived_only'},'onboarding_required'],
    [{status:'resolved',confidence:'high',matchedBy:['explicit_course_key'],course:{courseKey:'a',courseEntityId:'course:changed',displayName:'A'}},'context_unavailable'],
  ])('scheduled canonical status fails closed: %#',async(response,status)=>{
    const data=payload('scheduled');
    data.scheduledCourseContext={schemaVersion:1,source:'calendar_scheduled_wake',automationId:'auto',jobId:'job',runId:1,taskKind:'opp_coach_event_prompt',course:{ownerUserId:'u',agentId:'a',courseKey:'a',courseEntityId:'course:a',displayName:'A'},evidenceReadiness:'canonical_only'};
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(response),{status:200}));
    await expect(attachCourseContextForReviewedScope(data,{baseUrl:'https://t',secret:'s',fetcher})).resolves.toMatchObject({status});
  });
  test.each([['銷講',true],['三個秘密',true],['課綱',true],['課程',true],['老師回饋',true],['課程會議',true],['課程文件',true],['戰報',true],['招生 Offer',true],['提醒我明天繳電話費',false]])('%s => %s',(text,want)=>expect(requiresCourseContext(payload(text))).toBe(want));
  test('personal reminder bypasses skill, reviewed marker, and active binding unless course wording is explicit',()=>{
    expect(requiresCourseContext(payload('提醒我明天繳電話費',{courseScope:'reviewed'}),{courseSkillEnabled:true,hasActiveCourse:true})).toBe(false);
    expect(requiresCourseContext(payload('提醒我明天整理課程文件'),{courseSkillEnabled:true,hasActiveCourse:true})).toBe(true);
  });
  test('accepts the complete canonical ambiguous contract and preserves order',async()=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'ambiguous',reason:'alias_overlap',candidates:[candidate,{...candidate,courseKey:'a',courseEntityId:'course:a',displayName:'A 課'}]}),{status:200}));
    await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher})).resolves.toEqual({status:'clarification_required',candidates:[{courseKey:'b',displayName:'B 課'},{courseKey:'a',displayName:'A 課'}]});
  });
  test.each([
    [{status:'ambiguous',reason:'alias_overlap',candidates:[{courseKey:'b',displayName:'B'}]}],
    [{status:'ambiguous',reason:'unknown',candidates:[candidate]}],
    [{status:'ambiguous',reason:'alias_overlap',candidates:[{...candidate,status:'archived'}]}],
    [{status:'ambiguous',reason:'alias_overlap',candidates:[{...candidate,reasons:['unknown']}]}],
    [{status:'missing',reason:'no_match'}],
  ])('maps malformed closed contract %# to unavailable',async(body)=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(body),{status:200}));
    await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher})).resolves.toEqual({status:'context_unavailable',reasonCode:'resolver_unavailable'});
  });
  test.each(['no_courses','archived_only'] as const)('maps missing/%s to onboarding',async(reason)=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'missing',reason}),{status:200}));
    await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher})).resolves.toEqual({status:'onboarding_required'});
  });
  test.each(['multiple_active_courses','explicit_course_key_not_found'] as const)('allows empty candidate reasons for %s',async(reason)=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'ambiguous',reason,candidates:[{...candidate,reasons:[]}]}),{status:200}));
    await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher})).resolves.toMatchObject({status:'clarification_required'});
  });
  test.each(['explicit_course_key','message_name','message_alias','conversation_binding','single_course_default'] as const)('accepts and preserves resolved match %s',async(matchedBy)=>{
    const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({status:'resolved',confidence:'high',matchedBy:[matchedBy],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));
    const result=await attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher});
    expect(result).toMatchObject({status:'ready',context:{resolution:{matchedBy:[matchedBy]}}});
  });
  test.each([[],['unknown'],['message_name','message_alias']])('rejects invalid resolved matchedBy %j',async(matchedBy)=>{
    const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'resolved',confidence:'high',matchedBy,course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}}),{status:200}));
    await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher})).resolves.toEqual({status:'context_unavailable',reasonCode:'resolver_unavailable'});
  });
  test('personal reminder bypasses a failed session store read',async()=>{const manager={getSession:vi.fn().mockRejectedValue(new Error('down'))};await expect(attachCourseContextForReviewedScope(payload('提醒我明天繳電話費'),{baseUrl:'https://t',secret:'s',sessionManager:manager as never,sessionKey:'s'})).resolves.toEqual({status:'not_required'});expect(manager.getSession).not.toHaveBeenCalled();});
  test('accepts the real canonical Toolbox bundle shape and rejects identity mismatch',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['message_name'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const canonical={course:{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:['別名'],status:'active'},profile:{pmRole:null,teacher:null,collaborators:[],audience:null,coursePromise:null,resourceLocations:{}},context:{agentMd:'# 課程 X',contextPackId:'p',version:3,confidence:'high',generatedAt:'2026-07-09T03:00:00.000Z',lastIndexedAt:'2026-07-09T03:59:00.000Z',stale:false},evidence:{confirmed:[],candidates:[]}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonical),{status:200}));await expect(attachCourseContextForReviewedScope(payload('課程 X'),{baseUrl:'https://t',secret:'s',fetcher})).resolves.toMatchObject({status:'ready',context:{context:{confirmedSummary:'# 課程 X'}}});const mismatch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({...canonical,course:{...canonical.course,courseEntityId:'course:y'}}),{status:200}));await expect(attachCourseContextForReviewedScope(payload('課程 X'),{baseUrl:'https://t',secret:'s',fetcher:mismatch})).resolves.toMatchObject({status:'context_unavailable',reasonCode:'bundle_identity_mismatch'});});
  test('accepts producer-sized bundles above 12k and projects agentMd',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['message_name'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'x'}};const large:any=canonicalBundle('x');large.context.agentMd='a'.repeat(50000);large.evidence.confirmed=Array.from({length:30},(_,i)=>({id:String(i),sourceType:'doc',sourceId:String(i),sourceUrl:null,sourceTitle:null,excerptPreview:'e'.repeat(500),evidenceKind:'fact',confidence:'high',observedAt:'2026-07-11T00:00:00Z'}));const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(large),{status:200}));const result=await attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher});expect(result.status==='ready'&&result.context.context.confirmedSummary).toHaveLength(8000);large.context.agentMd+='x';const bad=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(large),{status:200}));await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher:bad})).resolves.toMatchObject({status:'context_unavailable'});});
  test('retrieval failure preserves ready canonical bundle',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));const memorySearch=vi.fn().mockRejectedValue(new Error('down'));const actual=payload('請整理課程 Offer');actual.organizationId='org';await expect(attachCourseContextForReviewedScope(actual,{baseUrl:'https://t',secret:'s',fetcher,memorySearch,courseSkillEnabled:true})).resolves.toMatchObject({status:'ready',context:{retrieval:{status:'degraded',crossCourseGuard:'passed',eventIds:[]}}});expect(memorySearch).toHaveBeenCalledWith(expect.objectContaining({entityIds:['course:x'],limit:8,query:expect.stringContaining('Offer')}));});
  test('empty retrieval emits the empty journey convention',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));const actual=payload('請整理課程');actual.organizationId='org';const events:Array<{event:string;status:string}>=[];await attachCourseContextForReviewedScope(actual,{baseUrl:'https://t',secret:'s',fetcher,memorySearch:vi.fn().mockResolvedValue([]),traceEmitter:async(event)=>{events.push(event);}});expect(events).toContainEqual(expect.objectContaining({event:'context.memory.empty',status:'ok'}));});
  test.each([
    ['loaded',[{id:1,payload_text:'safe',title:null,source_url:null,organization_id:'org',metadata:{owner_user_id:'u',agent_id:'a',course_entity_ids:['course:x']}}]],
    ['degraded',new Error('down')],
    ['invariant_violation',[{id:2,payload_text:'UNSAFE_EVENT_TEXT',title:null,source_url:null,organization_id:'org',metadata:{owner_user_id:'other',agent_id:'a',course_entity_ids:['course:x']}}]],
  ])('emits low-cardinality context.memory.%s without identity or content fields',async(expected,answer)=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));const actual=payload('SECRET_QUERY');actual.organizationId='org';const events:any[]=[];const memorySearch=answer instanceof Error?vi.fn().mockRejectedValue(answer):vi.fn().mockResolvedValue(answer);await attachCourseContextForReviewedScope(actual,{baseUrl:'https://t',secret:'s',fetcher,memorySearch,courseSkillEnabled:true,traceEmitter:async(event)=>{events.push(event);}});const event=events.find((item)=>item.event===`context.memory.${expected}`);expect(event).toMatchObject({candidate_count:expect.any(Number),safe_count:expect.any(Number),dropped_count:expect.any(Number),duration_ms:expect.any(Number)});for(const key of ['owner_hash','agent_key','course_entity_id','conversation_hash','query','message','snippet','prompt','header','result_count','course_key'])expect(event).not.toHaveProperty(key);expect(JSON.stringify(event)).not.toContain('SECRET_QUERY');expect(JSON.stringify(event)).not.toContain('UNSAFE_EVENT_TEXT');expect(JSON.stringify(event)).not.toContain('course:x');});
  test('persisted binding emits updated with ok status',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));const events:Array<{event:string;status:string}>=[];const sessionManager={getSessionStrict:vi.fn().mockResolvedValue(null),bindActiveCourse:vi.fn().mockResolvedValue({status:'persisted'})};await attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher,sessionManager:sessionManager as never,sessionKey:'s',traceEmitter:async(event)=>{events.push(event);}});expect(events).toContainEqual(expect.objectContaining({event:'context.binding.updated',status:'ok'}));});
  test('uses both advertised terms within three queries without querying context field names',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));const memorySearch=vi.fn().mockResolvedValue([]);const actual=payload('review now');actual.organizationId='org';await attachCourseContextForReviewedScope(actual,{baseUrl:'https://t',secret:'s',fetcher,memorySearch,courseSkillEnabled:true,courseSkillRetrievalTerms:['Key Learning','Offer'],courseSkillRetrievalLimit:3,courseSkillContextFields:['audience']});expect(memorySearch.mock.calls.map(([call])=>call.query)).toEqual(['review now','Key Learning','Offer']);expect(memorySearch).not.toHaveBeenCalledWith(expect.objectContaining({query:'audience'}));});
  test('projects only requested canonical fields and marks structurally unavailable fields missing',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const bundle=canonicalBundle('x');bundle.context.agentMd='SECRET_UNREQUESTED\nOffer invented in prose';bundle.profile.audience='課程 PM';bundle.profile.coursePromise='完成銷講';bundle.evidence.confirmed=[{id:'ev-1',sourceType:'doc',sourceId:'d',sourceUrl:null,sourceTitle:'正式論述',excerptPreview:'已確認證據',evidenceKind:'fact',confidence:'high',observedAt:'2026-07-11T00:00:00Z'}];const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(bundle),{status:200}));const result=await attachCourseContextForReviewedScope(payload('review now'),{baseUrl:'https://t',secret:'s',fetcher,courseSkillEnabled:true,courseSkillContextFields:['audience','course_promise','evidence','offer']});expect(result).toMatchObject({status:'ready'});const summary=result.status==='ready'?result.context.context.confirmedSummary:'';expect(summary).toContain('audience: 課程 PM');expect(summary).toContain('course_promise: 完成銷講');expect(summary).toContain('evidence:');expect(summary).toContain('正式論述');expect(summary).toContain('已確認證據');expect(summary).toContain('offer: [missing]');expect(summary).not.toContain('SECRET_UNREQUESTED');expect(summary).not.toContain('invented in prose');});
  test('uses only exact structured retrieval fields for readiness, preserving canonical conflicts with clarification',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const bundle=canonicalBundle('x');bundle.profile.audience='canonical audience';const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(bundle),{status:200}));const actual=payload('course_promise: prose must not count');actual.organizationId='org';const memorySearch=vi.fn().mockResolvedValue([{id:1,payload_text:'key_learning: prose must not count',title:null,source_url:null,organization_id:'org',metadata:{owner_user_id:'u',agent_id:'a',course_entity_ids:['course:x'],source_ref:'doc:1',course_readiness:{audience:'different audience',course_promise:'retrieved promise'}}}]);const result=await attachCourseContextForReviewedScope(actual,{baseUrl:'https://t',secret:'s',fetcher,memorySearch,courseSkillEnabled:true});expect(result).toMatchObject({status:'ready',context:{readiness:{level:'conflicted',answerPolicy:'answer_conservatively',availableFields:['audience','course_promise'],missingFields:['key_learning','existing_sales_talk'],suggestedQuestions:expect.arrayContaining([expect.stringContaining('受眾')])},evidence:[expect.objectContaining({kind:'canonical_context',fields:['audience']}),expect.objectContaining({kind:'fresh_course_retrieval',fields:['audience','course_promise']})]}});});
  test('empty retrieval remains advisory minimal and preserves canonical context',async()=>{const resolved={status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(resolved),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(canonicalBundle('x')),{status:200}));const actual=payload('課程');actual.organizationId='org';const result=await attachCourseContextForReviewedScope(actual,{baseUrl:'https://t',secret:'s',fetcher,memorySearch:vi.fn().mockResolvedValue([])});expect(result).toMatchObject({status:'ready',context:{context:{confirmedSummary:'s'},retrieval:{status:'empty'},readiness:{level:'minimal',answerPolicy:'answer_conservatively'}}});});
  test('non-text input is safe',()=>expect(requiresCourseContext({...payload('x'),messageText:undefined} as MessagePayload)).toBe(false));
  test('strict session outage fails a bound continuation closed',async()=>{const manager={getSessionStrict:vi.fn().mockRejectedValue(new Error('down'))};await expect(attachCourseContextForReviewedScope(payload('繼續'),{baseUrl:'https://t',secret:'s',sessionManager:manager as never,sessionKey:'s'})).resolves.toEqual({status:'context_unavailable',reasonCode:'session_unavailable'});});
  test('non-text attachment leaves pending selection untouched',async()=>{const pending={pendingId:'p',version:1,status:'pending',ownerUserId:'u',agentId:'a',candidates:[{courseKey:'x',displayName:'X'}],originalMessage:'task',createdAt:Date.now()};const manager={getSessionStrict:vi.fn().mockResolvedValue({pendingCourseSelection:pending}),claimPendingCourseSelection:vi.fn()};const result=await attachCourseContextForReviewedScope({...payload('x'),messageText:undefined} as MessagePayload,{baseUrl:'https://t',secret:'s',sessionManager:manager as never,sessionKey:'s'});expect(result).toEqual({status:'clarification_required',candidates:pending.candidates});expect(manager.claimPendingCourseSelection).not.toHaveBeenCalled();});
  test('pending set and expiry clear failures fail closed',async()=>{const ambiguous={status:'ambiguous',reason:'multiple_active_courses',candidates:[candidate]};const setManager={getSessionStrict:vi.fn().mockResolvedValue(null),createPendingCourseSelection:vi.fn().mockResolvedValue({status:'failed'})};const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(ambiguous),{status:200}));await expect(attachCourseContextForReviewedScope(payload('課程'),{baseUrl:'https://t',secret:'s',fetcher,sessionManager:setManager as never,sessionKey:'s'})).resolves.toMatchObject({status:'context_unavailable',reasonCode:'pending_write_failed'});const expired={pendingId:'old',version:1,status:'pending',ownerUserId:'u',agentId:'a',candidates:[{courseKey:'x',displayName:'X'}],originalMessage:'task',createdAt:0};const clearManager={getSessionStrict:vi.fn().mockResolvedValue({pendingCourseSelection:expired}),clearPendingCourseSelection:vi.fn().mockResolvedValue({status:'failed'})};await expect(attachCourseContextForReviewedScope(payload('繼續'),{baseUrl:'https://t',secret:'s',sessionManager:clearManager as never,sessionKey:'s'})).resolves.toMatchObject({status:'context_unavailable',reasonCode:'pending_clear_failed'});});
  test.each([
    ['legacy unscoped',{pendingId:'p',version:1,status:'pending',candidates:[{courseKey:'x',displayName:'X'}],originalMessage:'private',createdAt:Date.now()}],
    ['other owner',{pendingId:'p',version:1,status:'pending',ownerUserId:'other',agentId:'a',candidates:[{courseKey:'x',displayName:'X'}],originalMessage:'private',createdAt:Date.now()}],
    ['other agent',{pendingId:'p',version:1,status:'pending',ownerUserId:'u',agentId:'other',candidates:[{courseKey:'x',displayName:'X'}],originalMessage:'private',createdAt:Date.now()}],
  ])('fails closed without reading or replaying a %s pending record',async(_name,pending)=>{const manager={getSessionStrict:vi.fn().mockResolvedValue({pendingCourseSelection:pending}),claimPendingCourseSelection:vi.fn(),clearPendingCourseSelection:vi.fn()};await expect(attachCourseContextForReviewedScope(payload('1'),{baseUrl:'https://t',secret:'s',sessionManager:manager as never,sessionKey:'s'})).resolves.toEqual({status:'context_unavailable',reasonCode:'pending_scope_mismatch'});expect(manager.claimPendingCourseSelection).not.toHaveBeenCalled();expect(manager.clearPendingCourseSelection).not.toHaveBeenCalled();});
});
function canonicalBundle(key:string){return {course:{courseKey:key,courseEntityId:`course:${key}`,displayName:key,aliases:[],status:'active'},profile:{pmRole:null,teacher:null,collaborators:[],audience:null,coursePromise:null,resourceLocations:{}},context:{agentMd:'s',contextPackId:'p',version:1,confidence:'high',generatedAt:'2026-07-11T00:00:00Z',lastIndexedAt:null,stale:false},evidence:{confirmed:[],candidates:[]}};}
