import type { MessagePayload } from '@lobu/core';
import { afterEach, describe, expect, test, vi } from 'vitest';
import { MessageConsumer, terminalCourseContextSingletonKey, workerMessageSingletonKey } from '../orchestration/message-consumer.js';
import { __resetEncryptionKeyCacheForTests, verifyWorkerToken } from '@lobu/core';
const originalFetch=globalThis.fetch;
afterEach(()=>{delete process.env.TOOLBOX_COURSE_CONTEXT_URL;delete process.env.TOOLBOX_INTERNAL_SECRET;globalThis.fetch=originalFetch;});
const oppSkill={name:'opp-coach',repo:'local',enabled:true,content:`---\nname: opp-coach\nmetadata:\n  course-context-contract: 1\n  scope: course\n  context-fields: [audience, offer]\n  retrieval-terms: [Key Learning, Offer]\n  retrieval-limit: 3\n---`};
function setup(body:unknown, text='課程', metadata:Record<string,unknown>={}, rejectTerminal=false, withSession=true, rejectWorkerOnce=false, cleanupFails=false) {
  let handler:((job:{id:string;data:MessagePayload})=>Promise<void>)|undefined; const sends:Array<[string,unknown,unknown]>=[]; const order:string[]=[];
  let workerRejected=false;const queue={start:vi.fn(),stop:vi.fn(),createQueue:vi.fn(async(n)=>{order.push(`create:${n}`);}),work:vi.fn(async(_n,cb)=>{handler=cb;}),send:vi.fn(async(n,d,o)=>{order.push(`send:${n}`);sends.push([n,d,o]);if(rejectTerminal&&n==='thread_response')throw new Error('terminal failed');if(rejectWorkerOnce&&!workerRejected&&n.startsWith('thread_message_')){workerRejected=true;throw new Error('worker send failed');}return 'job';}),getQueueStats:vi.fn(),isHealthy:vi.fn(),pauseWorker:vi.fn(),resumeWorker:vi.fn()};
  const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{listDeployments:vi.fn().mockResolvedValue([]),createWorkerDeployment:vi.fn(),updateDeploymentActivity:vi.fn()} as never,queue as never);
  let cleanupFailed=false;let pending:any; if(withSession){const get=vi.fn(async()=>({shifuCourseContext:{courseKey:'old'},pendingCourseSelection:pending}));consumer.setSessionManager({getSession:get,getSessionStrict:get,bindActiveCourse:vi.fn(async()=>{order.push('bind');return {status:'persisted'};}),createPendingCourseSelection:vi.fn(async(_k,value)=>{pending={...value,pendingId:'pending-1',version:1,status:'pending'};return {status:'persisted',pending};}),claimPendingCourseSelection:vi.fn(async(_k,_id,_owner,_agent,key,messageId)=>{pending={...pending,status:'claimed',claimedAt:Date.now(),claimedCourseKey:key,claimedMessageId:messageId};return {status:'claimed',pending};}),markPendingCourseSelectionDispatched:vi.fn(async()=>{pending={...pending,status:'dispatched',dispatchedAt:Date.now()};return {status:'dispatched'};}),clearPendingCourseSelection:vi.fn(async()=>{if(cleanupFails&&!cleanupFailed){cleanupFailed=true;return {status:'failed'};}pending=undefined;return {status:'cleared'};})} as never);}
  process.env.TOOLBOX_COURSE_CONTEXT_URL='https://t';process.env.TOOLBOX_INTERNAL_SECRET='s';const fetcher=vi.fn();for(let value of (Array.isArray(body)?body:[body])){const record=value as Record<string,any>;if(record?.context?.confirmedSummary)value={course:{...record.course,aliases:[],status:'active'},profile:{pmRole:null,teacher:null,collaborators:[],audience:null,coursePromise:null,resourceLocations:{}},context:{agentMd:record.context.confirmedSummary,contextPackId:record.context.contextPackId,version:record.context.version,confidence:'high',generatedAt:'2026-07-11T00:00:00Z',lastIndexedAt:null,stale:record.context.stale},evidence:{confirmed:[],candidates:[]}};fetcher.mockResolvedValueOnce(new Response(JSON.stringify(value),{status:200}));}globalThis.fetch=fetcher as never;
  const data={userId:'u',agentId:'a',conversationId:'c',channelId:'ch',messageId:'m',platform:'line',messageText:text,platformMetadata:metadata,agentOptions:{}} as MessagePayload;
  return {sends,order,fetcher,consumer,data,run:async(nextText?:string,nextId?:string)=>{if(nextText)data.messageText=nextText;if(nextId)data.messageId=nextId;await consumer.start();return handler?.({id:'legacy',data});}};
}
describe('message consumer course boundary',()=>{
  test('worker idempotency key is stable per turn and distinct across canonical threads',()=>{const base={userId:'u',agentId:'a',conversationId:'c1',channelId:'ch',messageId:'same',platform:'line',messageText:'x',platformMetadata:{},agentOptions:{}} as MessagePayload;expect(workerMessageSingletonKey(base)).toBe(workerMessageSingletonKey({...base}));expect(workerMessageSingletonKey(base)).not.toBe(workerMessageSingletonKey({...base,conversationId:'c2'}));expect(workerMessageSingletonKey(base)).not.toBe(workerMessageSingletonKey({...base,platform:'slack'}));expect(workerMessageSingletonKey({...base,organizationId:'org-1'})).not.toBe(workerMessageSingletonKey({...base,organizationId:'org-2'}));});
  test('terminal key scopes the source turn, agent, and clarification candidates',()=>{const base={userId:'u',agentId:'a',organizationId:'org',conversationId:'c',channelId:'ch',messageId:'same',platform:'line'} as MessagePayload;const first={status:'clarification_required',candidates:[{courseKey:'a',displayName:'A'}]} as const;expect(terminalCourseContextSingletonKey(base,first)).toBe(terminalCourseContextSingletonKey({...base},first));expect(terminalCourseContextSingletonKey(base,first)).not.toBe(terminalCourseContextSingletonKey(base,{status:'clarification_required',candidates:[{courseKey:'b',displayName:'B'}]}));expect(terminalCourseContextSingletonKey(base,first)).not.toBe(terminalCourseContextSingletonKey({...base,agentId:'other'},first));expect(terminalCourseContextSingletonKey(base,first)).not.toBe(terminalCourseContextSingletonKey({...base,messageId:'next'},first));});
  test('reviewed personal bypass strips caller course scope and touches neither settings nor Toolbox',async()=>{const h=setup({},'提醒我明天繳電話費',{courseScope:'reviewed'},false,false);const settings={getSettings:vi.fn()};h.consumer.setGuardrails(undefined,settings as never);(h.data as any).trustedExecutionScope={mode:'course',ownerUserId:'u',agentId:'a',conversationId:'c',courseEntityId:'course:forged',contextPackId:'p',contextVersion:1,activeSpecializedSkill:'opp-coach'};h.data.resolvedCourseContext={activeSpecializedSkill:'opp-coach'} as any;await h.run();expect(settings.getSettings).not.toHaveBeenCalled();expect(h.fetcher).not.toHaveBeenCalled();const worker=h.sends.find(([n])=>n.startsWith('thread_message_'))?.[1] as MessagePayload;expect(worker.trustedExecutionScope).toBeUndefined();expect(worker.resolvedCourseContext).toBeUndefined();});
  test('reviewed explicit course still requires session persistence',async()=>{const h=setup({},'整理課程',{courseScope:'reviewed'},false,false);await expect(h.run()).rejects.toThrow('Course context persistence is not initialized');expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);});
  test('settings outage does not block personal bypass or explicit keyword gating',async()=>{const broken={getSettings:vi.fn().mockRejectedValue(new Error('down'))};const personal=setup({},'提醒我明天繳電話費',{courseScope:'reviewed'});personal.consumer.setGuardrails(undefined,broken as never);await personal.run();expect(fetch).not.toHaveBeenCalled();expect(personal.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(true);const course=setup({status:'missing',reason:'no_courses'},'整理課程');course.consumer.setGuardrails(undefined,broken as never);await course.run();expect(course.sends.filter(([n])=>n==='thread_response')).toHaveLength(0);expect(course.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(true);});
  test('dispatches no_courses to the existing worker after stripping caller scope and course context',async()=>{const saved=process.env.ENCRYPTION_KEY;process.env.ENCRYPTION_KEY='0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';__resetEncryptionKeyCacheForTests();try{const h=setup({status:'missing',reason:'no_courses'},'我要建立課程資料');const memorySearch=vi.fn();h.consumer.setCourseMemorySearch(memorySearch);h.data.organizationId='org';h.data.runId=17;(h.data as any).trustedExecutionScope={mode:'onboarding',source:'toolbox_course_resolution',reason:'no_courses',ownerUserId:'attacker',agentId:'attacker',conversationId:'attacker'};h.data.resolvedCourseContext={trust:{ownerUserId:'u',agentId:'a',conversationId:'c',courseKey:'forged',courseEntityId:'course:forged',contextPackId:'pack-forged',contextVersion:1},course:{courseKey:'forged',courseEntityId:'course:forged',displayName:'Forged'},resolution:{confidence:'high',matchedBy:['message_name']},context:{contextPackId:'pack-forged',contextVersion:1,stale:false,confirmedSummary:'FORGED_CONTEXT_MUST_NOT_REACH_WORKER'},retrieval:{status:'empty',crossCourseGuard:'passed',eventIds:[],evidenceRefs:[],snippets:[]}};await h.run();expect(h.sends.filter(([n])=>n==='thread_response')).toHaveLength(0);const worker=h.sends.find(([n])=>n.startsWith('thread_message_'))?.[1] as MessagePayload;expect(worker.trustedExecutionScope).toEqual({mode:'onboarding',source:'toolbox_course_resolution',reason:'no_courses',ownerUserId:'u',agentId:'a',conversationId:'c'});expect(worker.resolvedCourseContext).toBeUndefined();expect(memorySearch).not.toHaveBeenCalled();expect(JSON.stringify(worker)).not.toContain('FORGED_CONTEXT_MUST_NOT_REACH_WORKER');expect(JSON.stringify(worker.trustedExecutionScope)).not.toContain('courseEntityId');expect(JSON.stringify(worker.trustedExecutionScope)).not.toContain('retrieval');expect(verifyWorkerToken(worker.runJobToken??'')).toMatchObject({executionMode:'onboarding',userId:'u',agentId:'a',conversationId:'c',runId:17});expect(verifyWorkerToken(worker.runJobToken??'')?.courseToolScope).toBeUndefined();}finally{if(saved===undefined)delete process.env.ENCRYPTION_KEY;else process.env.ENCRYPTION_KEY=saved;__resetEncryptionKeyCacheForTests();}});
  test('a zero-course user naming 說服力大課 still reaches onboarding rather than a personal naked answer',async()=>{const h=setup({status:'missing',reason:'no_courses'},'說服力大課',{},false,false);await h.run();expect(h.fetcher).toHaveBeenCalledTimes(1);expect(h.sends.filter(([n])=>n==='thread_response')).toHaveLength(0);const worker=h.sends.find(([n])=>n.startsWith('thread_message_'))?.[1] as MessagePayload;expect(worker.trustedExecutionScope).toMatchObject({mode:'onboarding',reason:'no_courses'});expect(worker.resolvedCourseContext).toBeUndefined();});
  test('strict malformed ambiguous contract terminalizes and never dispatches worker',async()=>{const h=setup({status:'ambiguous',reason:'alias_overlap',candidates:[{courseKey:'x',displayName:'X'}]});await h.run();expect(h.sends.filter(([n])=>n==='thread_response')).toHaveLength(1);expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);});
  test('valid ambiguity and archived-only each terminalize once',async()=>{for(const body of [{status:'ambiguous',reason:'multiple_active_courses',candidates:[{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active',reasons:[]}]},{status:'missing',reason:'archived_only'}]){const h=setup(body);await h.run();expect(h.sends.filter(([n])=>n==='thread_response')).toHaveLength(1);expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);}});
  test('ready binds before arm and worker send',async()=>{const h=setup([{status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},{course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}}]);await h.run();const bind=h.order.indexOf('bind');const arm=h.order.findIndex((v,index)=>index>bind&&v.startsWith('create:'));const send=h.order.findIndex((v)=>v.startsWith('send:thread_message_'));expect(bind).toBeLessThan(arm);expect(arm).toBeLessThan(send);expect(h.sends.filter(([n])=>n.startsWith('thread_message_'))).toHaveLength(1);});
  test.each([
    ['幫我寫信跟老師確認下週錄課時間',null,'canonical summary'],
    ['整理今天的課程會議待辦',null,'canonical summary'],
    ['這堂課的三個秘密幫我想一下','opp-coach','Required course context'],
    ['幫我看這段銷講彩排哪裡要改','opp-coach','Required course context'],
  ] as const)('dispatches %s with general context and only activates opp-coach for sales talk',async(text,activeSpecializedSkill,summaryPart)=>{
    const h=setup([{status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},{course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'canonical summary'}}],text);
    h.consumer.setGuardrails(undefined,{getSettings:vi.fn().mockResolvedValue({skillsConfig:{skills:[{name:'opp-coach',repo:'local',enabled:true,content:`---\nname: opp-coach\nmetadata:\n  course-context-contract: 1\n  scope: course\n  context-fields: [audience, offer]\n  retrieval-terms: [Key Learning, Offer]\n  retrieval-limit: 8\n---`}]}})} as never);
    await h.run();
    const worker=h.sends.find(([name])=>name.startsWith('thread_message_'))?.[1] as MessagePayload;
    expect(worker.resolvedCourseContext?.activeSpecializedSkill).toBe(activeSpecializedSkill);
    expect(worker.resolvedCourseContext?.context.confirmedSummary).toContain(summaryPart);
    expect(worker.trustedExecutionScope).toMatchObject({mode:'course',activeSpecializedSkill});
  });
  test('installed opp-coach alone does not gate a neutral startup turn',async()=>{
    const h=setup({},'你好');
    h.consumer.setGuardrails(undefined,{getSettings:vi.fn().mockResolvedValue({skillsConfig:{skills:[{name:'opp-coach',repo:'local',enabled:true,content:`---\nname: opp-coach\nmetadata:\n  course-context-contract: 1\n  scope: course\n  context-fields: [audience]\n  retrieval-terms: [Offer]\n  retrieval-limit: 8\n---`}]}})} as never);
    await h.run();
    expect(h.fetcher).not.toHaveBeenCalled();
    const worker=h.sends.find(([name])=>name.startsWith('thread_message_'))?.[1] as MessagePayload;
    expect(worker.resolvedCourseContext).toBeUndefined();
    expect(worker.trustedExecutionScope).toBeUndefined();
  });
  test('caller metadata taskKind cannot activate opp-coach',async()=>{
    const h=setup({},'你好',{taskKind:'sales_rehearsal'});
    h.consumer.setGuardrails(undefined,{getSettings:vi.fn().mockResolvedValue({skillsConfig:{skills:[oppSkill]}})} as never);
    await h.run();
    expect(h.fetcher).not.toHaveBeenCalled();
    const worker=h.sends.find(([name])=>name.startsWith('thread_message_'))?.[1] as MessagePayload;
    expect(worker.resolvedCourseContext).toBeUndefined();
    expect(worker.trustedExecutionScope).toBeUndefined();
  });
  test('generic PM work does not inherit inactive opp-coach retrieval limit',async()=>{
    const h=setup([{status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},{course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'canonical summary'}}],'整理今天的課程會議待辦');
    h.data.organizationId='org';
    const memorySearch=vi.fn().mockResolvedValue([]);
    h.consumer.setCourseMemorySearch(memorySearch);
    h.consumer.setGuardrails(undefined,{getSettings:vi.fn().mockResolvedValue({skillsConfig:{skills:[oppSkill]}})} as never);
    await h.run();
    expect(memorySearch).toHaveBeenCalledWith(expect.objectContaining({limit:8,query:'整理今天的課程會議待辦'}));
    expect(memorySearch).toHaveBeenCalledTimes(1);
    const worker=h.sends.find(([name])=>name.startsWith('thread_message_'))?.[1] as MessagePayload;
    expect(worker.resolvedCourseContext?.activeSpecializedSkill).toBeNull();
  });
  test('legacy unscoped course-memory candidates violate hydration and never dispatch',async()=>{const h=setup([{status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},{course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'canonical summary'}}]);h.data.organizationId='org';h.consumer.setCourseMemorySearch(vi.fn().mockResolvedValue([{id:7,payload_text:'legacy-unscoped-text',title:'legacy',source_url:null,organization_id:'org',metadata:{agent_id:'a'}}]));await h.run();expect(h.sends.filter(([name])=>name.startsWith('thread_message_'))).toHaveLength(0);expect(JSON.stringify(h.sends)).not.toContain('legacy-unscoped-text');});
  test('bound course conversation match persists into the dispatched context',async()=>{const h=setup([{status:'resolved',confidence:'high',matchedBy:['conversation_binding'],course:{courseKey:'old',courseEntityId:'course:old',displayName:'Old'}},{course:{courseKey:'old',courseEntityId:'course:old',displayName:'Old'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}}],'繼續');await h.run();expect(JSON.parse((h.fetcher.mock.calls[0]?.[1] as RequestInit).body as string)).toMatchObject({boundCourseKey:'old'});const worker=h.sends.find(([n])=>n.startsWith('thread_message_'))?.[1] as MessagePayload;expect(worker.resolvedCourseContext?.resolution.matchedBy).toEqual(['conversation_binding']);const bind=h.order.indexOf('bind');const arm=h.order.findIndex((v,index)=>index>bind&&v.startsWith('create:'));expect(bind).toBeLessThan(arm);expect(arm).toBeLessThan(h.order.findIndex((v)=>v.startsWith('send:thread_message_')));});
  test('archived-only durable receipt migration fails terminal enqueue closed with zero worker dispatch',async()=>{const h=setup({status:'missing',reason:'archived_only'},'課程',{},true);await expect(h.run()).rejects.toThrow('Failed to process message job');expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);const terminal=h.sends.find(([name])=>name==='thread_response');expect(terminal?.[2]).toMatchObject({durableSingleton:true,singletonKey:expect.stringMatching(/^course-terminal:/)});});
  test('selection 1 replays the bounded original task with explicit course key',async()=>{const ambiguous={status:'ambiguous',reason:'multiple_active_courses',candidates:[{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active',reasons:[]}]};const resolved={status:'resolved',confidence:'high',matchedBy:['explicit_course_key'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const h=setup([ambiguous,resolved,{course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}}],'整理課程戰報');await h.run();await h.run('1');expect(JSON.parse((h.fetcher.mock.calls[1]?.[1] as RequestInit).body as string)).toMatchObject({explicitCourseKey:'x',message:'整理課程戰報'});const worker=h.sends.findLast(([n])=>n.startsWith('thread_message_'))?.[1] as MessagePayload;expect(worker.messageText).toBe('整理課程戰報');});
  test('send failure keeps claimed original task for retry',async()=>{const ambiguous={status:'ambiguous',reason:'multiple_active_courses',candidates:[{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active',reasons:[]}]};const resolved={status:'resolved',confidence:'high',matchedBy:['explicit_course_key'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const bundle={course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}};const h=setup([ambiguous,resolved,bundle,resolved,bundle],'整理課程戰報',{},false,true,true);await h.run();await expect(h.run('1')).rejects.toThrow();await h.run('1');const attempts=h.sends.filter(([n])=>n.startsWith('thread_message_'));expect(attempts).toHaveLength(2);expect((attempts[1]?.[1] as MessagePayload).messageText).toBe('整理課程戰報');});
  test('cleanup failure recovers without duplicate dispatch',async()=>{const ambiguous={status:'ambiguous',reason:'multiple_active_courses',candidates:[{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active',reasons:[]}]};const resolved={status:'resolved',confidence:'high',matchedBy:['explicit_course_key'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}};const bundle={course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}};const h=setup([ambiguous,resolved,bundle,{status:'missing',reason:'archived_only'}],'整理課程戰報',{},false,true,false,true);await h.run();await h.run('1');await h.run('1');expect(h.sends.filter(([n])=>n.startsWith('thread_message_'))).toHaveLength(1);await h.run('整理課程','m-next');expect(h.sends.filter(([n])=>n.startsWith('thread_message_'))).toHaveLength(1);expect(h.sends.some(([n])=>n==='thread_response')).toBe(true);});
});
