import type { MessagePayload } from '@lobu/core';
import { afterEach, describe, expect, test, vi } from 'vitest';
import { MessageConsumer } from '../orchestration/message-consumer.js';
const originalFetch=globalThis.fetch;
afterEach(()=>{delete process.env.TOOLBOX_COURSE_CONTEXT_URL;delete process.env.TOOLBOX_INTERNAL_SECRET;globalThis.fetch=originalFetch;});
function setup(body:unknown, text='課程', metadata:Record<string,unknown>={}, rejectTerminal=false) {
  let handler:((job:{id:string;data:MessagePayload})=>Promise<void>)|undefined; const sends:Array<[string,unknown,unknown]>=[]; const order:string[]=[];
  const queue={start:vi.fn(),stop:vi.fn(),createQueue:vi.fn(async(n)=>{order.push(`create:${n}`);}),work:vi.fn(async(_n,cb)=>{handler=cb;}),send:vi.fn(async(n,d,o)=>{order.push(`send:${n}`);sends.push([n,d,o]);if(rejectTerminal&&n==='thread_response')throw new Error('terminal failed');return 'job';}),getQueueStats:vi.fn(),isHealthy:vi.fn(),pauseWorker:vi.fn(),resumeWorker:vi.fn()};
  const consumer=new MessageConsumer({queues:{expireInSeconds:1,retryLimit:1}} as never,{listDeployments:vi.fn().mockResolvedValue([]),createWorkerDeployment:vi.fn(),updateDeploymentActivity:vi.fn()} as never,queue as never);
  consumer.setSessionManager({getSession:vi.fn().mockResolvedValue({shifuCourseContext:{courseKey:'old'}}),bindActiveCourse:vi.fn(async()=>{order.push('bind');return {status:'persisted'};})} as never);
  process.env.TOOLBOX_COURSE_CONTEXT_URL='https://t';process.env.TOOLBOX_INTERNAL_SECRET='s';const fetcher=vi.fn();for(const value of (Array.isArray(body)?body:[body]))fetcher.mockResolvedValueOnce(new Response(JSON.stringify(value),{status:200}));globalThis.fetch=fetcher as never;
  const data={userId:'u',agentId:'a',conversationId:'c',channelId:'ch',messageId:'m',platform:'line',messageText:text,platformMetadata:metadata,agentOptions:{}} as MessagePayload;
  return {sends,order,fetcher,run:async()=>{await consumer.start();return handler?.({id:'legacy',data});}};
}
describe('message consumer course boundary',()=>{
  test('personal reminder bypasses reviewed and active binding without Toolbox',async()=>{const h=setup({},'提醒我明天繳電話費',{courseScope:'reviewed'});await h.run();expect(fetch).not.toHaveBeenCalled();expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(true);});
  test('strict malformed ambiguous contract terminalizes and never dispatches worker',async()=>{const h=setup({status:'ambiguous',reason:'alias_overlap',candidates:[{courseKey:'x',displayName:'X'}]});await h.run();expect(h.sends.filter(([n])=>n==='thread_response')).toHaveLength(1);expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);});
  test('valid ambiguity and missing each terminalize once',async()=>{for(const body of [{status:'ambiguous',reason:'multiple_active_courses',candidates:[{courseKey:'x',courseEntityId:'course:x',displayName:'X',aliases:[],status:'active',reasons:[]}]},{status:'missing',reason:'no_courses'}]){const h=setup(body);await h.run();expect(h.sends.filter(([n])=>n==='thread_response')).toHaveLength(1);expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);}});
  test('ready binds before arm and worker send',async()=>{const h=setup([{status:'resolved',confidence:'high',matchedBy:['single_course_default'],course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'}},{course:{courseKey:'x',courseEntityId:'course:x',displayName:'X'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}}]);await h.run();const bind=h.order.indexOf('bind');const arm=h.order.findIndex((v,index)=>index>bind&&v.startsWith('create:'));const send=h.order.findIndex((v)=>v.startsWith('send:thread_message_'));expect(bind).toBeLessThan(arm);expect(arm).toBeLessThan(send);expect(h.sends.filter(([n])=>n.startsWith('thread_message_'))).toHaveLength(1);});
  test('bound course conversation match persists into the dispatched context',async()=>{const h=setup([{status:'resolved',confidence:'high',matchedBy:['conversation_binding'],course:{courseKey:'old',courseEntityId:'course:old',displayName:'Old'}},{course:{courseKey:'old',courseEntityId:'course:old',displayName:'Old'},context:{contextPackId:'p',version:1,stale:false,confirmedSummary:'s'}}],'繼續');await h.run();expect(JSON.parse((h.fetcher.mock.calls[0]?.[1] as RequestInit).body as string)).toMatchObject({boundCourseKey:'old'});const worker=h.sends.find(([n])=>n.startsWith('thread_message_'))?.[1] as MessagePayload;expect(worker.resolvedCourseContext?.resolution.matchedBy).toEqual(['conversation_binding']);const bind=h.order.indexOf('bind');const arm=h.order.findIndex((v,index)=>index>bind&&v.startsWith('create:'));expect(bind).toBeLessThan(arm);expect(arm).toBeLessThan(h.order.findIndex((v)=>v.startsWith('send:thread_message_')));});
  test('terminal send rejection propagates with zero worker dispatch',async()=>{const h=setup({status:'missing',reason:'no_courses'},'課程',{},true);await expect(h.run()).rejects.toThrow('Failed to process message job');expect(h.sends.some(([n])=>n.startsWith('thread_message_'))).toBe(false);});
});
